#!/bin/bash
echo "================================================"
echo "  ACLs and Advanced Permissions Reference"
echo "  Linux+ XK0-006 Domain 3: Security"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "--- STANDARD PERMISSIONS REVIEW ---"
echo ""
echo "  chmod numeric:"
echo "    r=4  w=2  x=1"
echo "    chmod 755 file    rwxr-xr-x"
echo "    chmod 644 file    rw-r--r--"
echo "    chmod 700 file    rwx------"
echo "    chmod 600 file    rw-------"
echo ""
echo "  chmod symbolic:"
echo "    chmod u+x file    Add execute for owner"
echo "    chmod g-w file    Remove write for group"
echo "    chmod o=r file    Set others to read only"
echo "    chmod a+r file    Add read for all"
echo "    u=owner  g=group  o=others  a=all"

echo ""
echo "--- SPECIAL PERMISSIONS (exam heavy) ---"
echo ""
echo "  SUID (Set User ID) - 4000"
echo "    chmod u+s file    or    chmod 4755 file"
echo "    When executed, runs as the FILE OWNER, not the user"
echo "    Example: /usr/bin/passwd has SUID"
echo "    ls shows: -rwsr-xr-x"
echo "    The 's' in owner execute = SUID is set"
echo "    Security risk: SUID on wrong binary = privilege escalation"
echo ""
echo "  SGID (Set Group ID) - 2000"
echo "    chmod g+s file    or    chmod 2755 file"
echo "    On files: runs as the file GROUP"
echo "    On directories: new files inherit the directory group"
echo "    ls shows: -rwxr-sr-x"
echo "    The 's' in group execute = SGID is set"
echo "    Common use: shared team directories"
echo ""
echo "  Sticky Bit - 1000"
echo "    chmod +t directory    or    chmod 1755 directory"
echo "    Only file owner can delete their files in the directory"
echo "    Even if others have write permission"
echo "    ls shows: drwxrwxrwt"
echo "    The 't' in others execute = sticky bit"
echo "    Example: /tmp has sticky bit (everyone writes, only owner deletes)"
echo ""
echo "  Find special permissions:"
echo "    find / -perm -4000    Find all SUID files"
echo "    find / -perm -2000    Find all SGID files"
echo "    find / -perm -1000    Find all sticky bit dirs"

echo ""
echo "--- ACLs (Access Control Lists) ---"
echo ""
echo "  ACLs add permissions BEYOND standard owner/group/other"
echo "  When standard chmod is not granular enough"
echo ""
echo "  View ACLs:"
echo "    getfacl file"
echo ""
echo "  Set ACLs:"
echo "    setfacl -m u:john:rw file        Give john read/write"
echo "    setfacl -m g:devteam:rx file     Give devteam group read/exec"
echo "    setfacl -m o::r file             Set others to read"
echo "    setfacl -m u:john:--- file       Remove all access for john"
echo ""
echo "  Remove ACLs:"
echo "    setfacl -x u:john file           Remove john ACL entry"
echo "    setfacl -b file                  Remove ALL ACLs"
echo ""
echo "  Default ACLs (inherited by new files in directory):"
echo "    setfacl -m d:u:john:rw directory"
echo "    setfacl -m d:g:devteam:rx directory"
echo ""
echo "  How to tell a file has ACLs:"
echo "    ls -l shows a + at end of permissions"
echo "    -rw-r--r--+  <-- the + means ACLs exist"

echo ""
echo "--- CHOWN AND CHGRP ---"
echo ""
echo "  Change ownership:"
echo "    chown user file              Change owner"
echo "    chown user:group file        Change owner and group"
echo "    chown :group file            Change group only"
echo "    chown -R user:group dir/     Recursive (all contents)"
echo ""
echo "  Change group:"
echo "    chgrp group file             Change group"
echo "    chgrp -R group dir/          Recursive"
echo ""
echo "  Only root can change owner (chown)"
echo "  Users can change group to groups they belong to"

echo ""
echo "--- UMASK ---"
echo ""
echo "  umask sets DEFAULT permissions for new files"
echo ""
echo "  How it works:"
echo "    Files default:      666 (no execute)"
echo "    Directories default: 777"
echo "    Subtract the umask to get actual permissions"
echo ""
echo "  umask 022 (common default):"
echo "    Files:       666 - 022 = 644 (rw-r--r--)"
echo "    Directories: 777 - 022 = 755 (rwxr-xr-x)"
echo ""
echo "  umask 077 (restrictive):"
echo "    Files:       666 - 077 = 600 (rw-------)"
echo "    Directories: 777 - 077 = 700 (rwx------)"
echo ""
echo "  Commands:"
echo "    umask              Show current umask"
echo "    umask 027           Set umask for this session"
echo "    /etc/profile        System-wide umask setting"
echo "    ~/.bashrc            User-specific umask"

echo ""
echo "--- FILE ATTRIBUTES (beyond permissions) ---"
echo ""
echo "  View attributes:"
echo "    lsattr file"
echo ""
echo "  Set attributes:"
echo "    chattr +i file     Immutable (cannot be modified or deleted)"
echo "    chattr +a file     Append only (can add, cannot modify)"
echo "    chattr -i file     Remove immutable"
echo ""
echo "  Immutable means even root cannot delete the file"
echo "  Must remove attribute first: chattr -i file"
echo ""
echo "  Common exam scenario:"
echo "    Q: Root cannot delete a file. Why?"
echo "    A: chattr +i was set. Use lsattr to check."

echo ""
echo "--- PAM (Pluggable Authentication Modules) ---"
echo ""
echo "  PAM controls how authentication works"
echo "  Config location: /etc/pam.d/"
echo ""
echo "  PAM module types:"
echo "    auth       Verify identity (password, key, biometric)"
echo "    account    Check account restrictions (expired, locked)"
echo "    password   Change passwords (complexity, history)"
echo "    session    Setup/cleanup after login (limits, logging)"
echo ""
echo "  PAM control flags:"
echo "    required     Must pass, continue checking"
echo "    requisite    Must pass, stop immediately if fail"
echo "    sufficient   If passes, skip remaining"
echo "    optional     Result doesn't matter unless only module"
echo ""
echo "  Common PAM modules:"
echo "    pam_unix.so       Standard password authentication"
echo "    pam_ldap.so       LDAP authentication"
echo "    pam_pwquality.so  Password complexity rules"
echo "    pam_tally2.so     Account lockout after failures"
echo "    pam_limits.so     Resource limits (/etc/security/limits.conf)"

echo ""
echo "--- ENCRYPTION ---"
echo ""
echo "  LUKS (disk encryption):"
echo "    cryptsetup luksFormat /dev/sda3        Encrypt partition"
echo "    cryptsetup luksOpen /dev/sda3 secure   Unlock"
echo "    cryptsetup luksClose secure            Lock"
echo ""
echo "  GPG (file encryption):"
echo "    gpg -c file.txt                Encrypt with password"
echo "    gpg file.txt.gpg               Decrypt"
echo "    gpg --gen-key                  Generate key pair"
echo "    gpg -e -r user file.txt        Encrypt for specific user"

echo ""
echo "ACL and security reference complete."
