#!/bin/bash
echo "================================================"
echo "  Automation and Orchestration Reference"
echo "  Linux+ XK0-006 Domain 4"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== CONFIGURATION MANAGEMENT TOOLS ==="
echo ""
echo "  Ansible:"
echo "    Agentless (uses SSH)"
echo "    Written in YAML (playbooks)"
echo "    Push-based (you run it, it pushes changes)"
echo "    Python-based"
echo "    Inventory: /etc/ansible/hosts"
echo ""
echo "    ansible all -m ping                  Test connectivity"
echo "    ansible all -a 'uptime'              Run command"
echo "    ansible-playbook deploy.yml          Run playbook"
echo ""
echo "    Example playbook (deploy.yml):"
echo "    ---"
echo "    - hosts: webservers"
echo "      become: yes"
echo "      tasks:"
echo "        - name: Install nginx"
echo "          apt:"
echo "            name: nginx"
echo "            state: present"
echo "        - name: Start nginx"
echo "          service:"
echo "            name: nginx"
echo "            state: started"
echo "            enabled: yes"
echo ""
echo "  Puppet:"
echo "    Agent-based (agent runs on each server)"
echo "    Uses its own DSL (manifests)"
echo "    Pull-based (agents pull config from server)"
echo "    Ruby-based"
echo ""
echo "  Chef:"
echo "    Agent-based"
echo "    Uses Ruby DSL (recipes/cookbooks)"
echo "    Pull-based"
echo ""
echo "  SaltStack:"
echo "    Agent or agentless"
echo "    YAML configuration"
echo "    Push or pull"
echo ""
echo "  Exam focus: know what each tool does"
echo "  Ansible is most common in exam questions"

echo ""
echo "=== INFRASTRUCTURE AS CODE ==="
echo ""
echo "  Terraform:"
echo "    Provisions infrastructure (VMs, networks, storage)"
echo "    Declarative (you describe desired state)"
echo "    Cloud-agnostic (AWS, Azure, GCP)"
echo "    State file tracks what exists"
echo ""
echo "    terraform init       Initialize"
echo "    terraform plan       Preview changes"
echo "    terraform apply      Create infrastructure"
echo "    terraform destroy    Remove everything"
echo ""
echo "  CloudFormation:"
echo "    AWS-specific version of Terraform"
echo "    YAML or JSON templates"
echo ""
echo "  Key difference:"
echo "    Terraform = creates the servers"
echo "    Ansible = configures the servers"
echo "    Use both together"

echo ""
echo "=== VERSION CONTROL (Git) ==="
echo ""
echo "  Core commands:"
echo "    git init                      New repository"
echo "    git clone url                 Copy remote repo"
echo "    git add file                  Stage changes"
echo "    git add .                     Stage all changes"
echo "    git commit -m 'message'       Save snapshot"
echo "    git push                      Upload to remote"
echo "    git pull                      Download from remote"
echo "    git status                    Check current state"
echo "    git log --oneline             Commit history"
echo "    git diff                      Show changes"
echo ""
echo "  Branching:"
echo "    git branch                    List branches"
echo "    git branch feature            Create branch"
echo "    git checkout feature          Switch to branch"
echo "    git checkout -b feature       Create and switch"
echo "    git merge feature             Merge into current"
echo "    git branch -d feature         Delete branch"
echo ""
echo "  Remote:"
echo "    git remote -v                 Show remote URLs"
echo "    git remote add origin url     Add remote"
echo "    git fetch                     Download without merge"

echo ""
echo "=== CI/CD CONCEPTS ==="
echo ""
echo "  Continuous Integration (CI):"
echo "    Developers merge code frequently"
echo "    Automated builds and tests run on every merge"
echo "    Catches bugs early"
echo "    Tools: Jenkins, GitLab CI, GitHub Actions"
echo ""
echo "  Continuous Delivery (CD):"
echo "    Code is always ready to deploy"
echo "    Deploy to staging automatically"
echo "    Deploy to production with manual approval"
echo ""
echo "  Continuous Deployment:"
echo "    Same as delivery but fully automated"
echo "    Every passing build goes to production"
echo "    No manual approval needed"
echo ""
echo "  Pipeline stages:"
echo "    Source -> Build -> Test -> Deploy"
echo ""
echo "  CI/CD in practice:"
echo "    1. Developer pushes code"
echo "    2. CI server detects change"
echo "    3. Builds the application"
echo "    4. Runs automated tests"
echo "    5. If tests pass, deploys to staging"
echo "    6. Manual or auto deploy to production"

echo ""
echo "=== CLOUD CONCEPTS ==="
echo ""
echo "  Service models:"
echo "    IaaS  Infrastructure as a Service (VMs, network)"
echo "          AWS EC2, Azure VMs, Google Compute"
echo "          You manage: OS, apps, data"
echo ""
echo "    PaaS  Platform as a Service (runtime environment)"
echo "          Heroku, Azure App Service, Google App Engine"
echo "          You manage: apps and data only"
echo ""
echo "    SaaS  Software as a Service (full application)"
echo "          Gmail, Office 365, Salesforce"
echo "          You manage: just your data"
echo ""
echo "  Deployment models:"
echo "    Public    Shared infrastructure (AWS, Azure)"
echo "    Private   Dedicated to one organization"
echo "    Hybrid    Mix of public and private"
echo "    Community Shared by similar organizations"

echo ""
echo "=== ORCHESTRATION ==="
echo ""
echo "  Kubernetes (container orchestration):"
echo "    kubectl get pods               List pods"
echo "    kubectl get nodes              List nodes"
echo "    kubectl apply -f file.yaml     Deploy config"
echo "    kubectl scale deploy name --replicas=5"
echo "    kubectl logs pod_name          View logs"
echo "    kubectl exec -it pod -- sh     Shell into pod"
echo ""
echo "  Docker Compose (multi-container):"
echo "    docker compose up -d           Start all services"
echo "    docker compose down            Stop all services"
echo "    docker compose ps              List services"
echo "    docker compose logs            View all logs"
echo "    docker-compose.yml             Config file"

echo ""
echo "=== AUTOMATION SCRIPTING PATTERNS ==="
echo ""
echo "  Idempotent operations (safe to run multiple times):"
echo "    mkdir -p /dir       OK if exists"
echo "    useradd -m user     Fails if exists (check first)"
echo ""
echo "  Check before act:"
echo "    if ! id user 2>/dev/null; then"
echo "        useradd -m user"
echo "    fi"
echo ""
echo "  Error handling:"
echo "    set -euo pipefail   Exit on any error"
echo "    command || echo 'Failed'"
echo "    command && echo 'Succeeded'"
echo ""
echo "  Logging:"
echo "    exec > >(tee -a /var/log/script.log)"
echo "    exec 2>&1"
echo "    echo \"[\$(date)] Starting script\""

echo ""
echo "Automation and orchestration reference complete."
