#!/bin/bash
echo "================================================"
echo "  Backup and Recovery Reference"
echo "  Linux+ XK0-006"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== BACKUP TYPES ==="
echo ""
echo "  Full backup:"
echo "    Copies everything. Largest size. Slowest."
echo "    Restore: only need this one backup."
echo ""
echo "  Incremental backup:"
echo "    Only files changed since LAST backup (any type)."
echo "    Smallest size. Fastest."
echo "    Restore: need full + every incremental in order."
echo ""
echo "  Differential backup:"
echo "    Only files changed since LAST FULL backup."
echo "    Medium size. Medium speed."
echo "    Restore: need full + latest differential only."
echo ""
echo "  Exam trick: incremental vs differential"
echo "    Incremental = since last backup (any)"
echo "    Differential = since last FULL backup"

echo ""
echo "=== TAR (archive and backup) ==="
echo ""
echo "  Create:"
echo "    tar cf backup.tar /data           Create archive"
echo "    tar czf backup.tar.gz /data       Create + gzip"
echo "    tar cjf backup.tar.bz2 /data      Create + bzip2"
echo "    tar cJf backup.tar.xz /data       Create + xz"
echo ""
echo "  Extract:"
echo "    tar xf backup.tar                 Extract"
echo "    tar xzf backup.tar.gz             Extract gzipped"
echo "    tar xjf backup.tar.bz2            Extract bzip2"
echo "    tar xf backup.tar -C /target      Extract to directory"
echo ""
echo "  List contents:"
echo "    tar tf backup.tar                 List files"
echo ""
echo "  Flags: c=create x=extract t=list f=file"
echo "         z=gzip j=bzip2 J=xz v=verbose"
echo ""
echo "  Compression comparison:"
echo "    gzip    Fast compression, moderate ratio"
echo "    bzip2   Slower, better ratio"
echo "    xz      Slowest, best ratio"

echo ""
echo "=== RSYNC (incremental copy) ==="
echo ""
echo "  Local sync:"
echo "    rsync -av /source/ /destination/"
echo ""
echo "  Remote sync:"
echo "    rsync -avz /local/ user@server:/remote/"
echo "    rsync -avz user@server:/remote/ /local/"
echo ""
echo "  Flags:"
echo "    -a   Archive (preserves permissions, ownership, timestamps)"
echo "    -v   Verbose"
echo "    -z   Compress during transfer"
echo "    -e ssh  Use SSH for transport"
echo "    --delete  Remove files in dest that don't exist in source"
echo "    --dry-run  Show what would happen without doing it"
echo "    --exclude '*.log'  Skip log files"
echo ""
echo "  Trailing slash matters:"
echo "    rsync -av /data/ /backup/    Copies CONTENTS of data"
echo "    rsync -av /data /backup/     Copies data DIRECTORY itself"

echo ""
echo "=== DD (disk-level copy) ==="
echo ""
echo "  Clone entire disk:"
echo "    dd if=/dev/sda of=/dev/sdb bs=64K status=progress"
echo ""
echo "  Create disk image:"
echo "    dd if=/dev/sda of=/backup/disk.img bs=64K"
echo ""
echo "  Write ISO to USB:"
echo "    dd if=linux.iso of=/dev/sdb bs=4M status=progress"
echo ""
echo "  Wipe a disk:"
echo "    dd if=/dev/zero of=/dev/sda bs=1M"
echo ""
echo "  if = input file (source)"
echo "  of = output file (destination)"
echo "  bs = block size"
echo ""
echo "  WARNING: dd has no confirmation. Wrong of= destroys data."
echo "  Known as 'disk destroyer' for a reason."

echo ""
echo "=== CPIO (archive format) ==="
echo ""
echo "  Create archive from file list:"
echo "    find /etc -name '*.conf' | cpio -o > configs.cpio"
echo ""
echo "  Extract:"
echo "    cpio -id < configs.cpio"
echo ""
echo "  Used by initramfs and RPM packages internally"

echo ""
echo "=== SNAPSHOT AND RESTORE ==="
echo ""
echo "  LVM snapshots:"
echo "    lvcreate -L 5G -s -n snap_data /dev/vg/lv_data"
echo "    mount /dev/vg/snap_data /mnt/snapshot"
echo "    (read snapshot while original keeps running)"
echo "    lvremove /dev/vg/snap_data"
echo ""
echo "  Btrfs snapshots:"
echo "    btrfs subvolume snapshot /data /data/.snap_20260628"
echo "    btrfs subvolume delete /data/.snap_20260628"
echo ""
echo "  VM snapshots:"
echo "    Take before patching or major changes"
echo "    Fastest rollback if something breaks"

echo ""
echo "=== BACKUP STRATEGY ==="
echo ""
echo "  3-2-1 Rule:"
echo "    3 copies of data"
echo "    2 different media types"
echo "    1 offsite copy"
echo ""
echo "  Typical schedule:"
echo "    Weekly full backup (Sunday night)"
echo "    Daily incremental (Mon-Sat)"
echo "    Monthly archive to offsite/cloud"
echo ""
echo "  Test restores regularly!"
echo "  A backup you can't restore is not a backup."

echo ""
echo "Backup and recovery reference complete."
