#!/bin/bash
echo "================================================"
echo "  Containers and Virtualization Reference"
echo "  Linux+ XK0-006"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== VIRTUALIZATION TYPES ==="
echo ""
echo "  Type 1 - Bare Metal Hypervisor:"
echo "    Runs directly on hardware"
echo "    VMware ESXi, KVM, Microsoft Hyper-V, Xen"
echo "    Used in data centers and production"
echo ""
echo "  Type 2 - Hosted Hypervisor:"
echo "    Runs on top of an OS"
echo "    VirtualBox, VMware Workstation, Parallels"
echo "    Used for development and testing"
echo ""
echo "  KVM (Kernel-based Virtual Machine):"
echo "    Built into Linux kernel"
echo "    Uses /dev/kvm device"
echo "    Managed with libvirt and virsh"
echo ""
echo "  KVM commands:"
echo "    virsh list --all              List all VMs"
echo "    virsh start vm_name           Start VM"
echo "    virsh shutdown vm_name        Graceful shutdown"
echo "    virsh destroy vm_name         Force stop"
echo "    virsh console vm_name         Console access"
echo "    virsh dominfo vm_name         VM details"
echo "    virt-install                  Create new VM"

echo ""
echo "=== CONTAINERS vs VMs ==="
echo ""
echo "  Virtual Machines:"
echo "    + Full OS isolation (own kernel)"
echo "    + Strong security boundaries"
echo "    - Heavy (GB of disk per VM)"
echo "    - Slow to start (minutes)"
echo "    - More resource overhead"
echo ""
echo "  Containers:"
echo "    + Lightweight (MB not GB)"
echo "    + Start in seconds"
echo "    + Share host kernel"
echo "    + Efficient resource usage"
echo "    - Less isolation than VMs"
echo "    - Share kernel = shared vulnerabilities"

echo ""
echo "=== DOCKER ==="
echo ""
echo "  Container lifecycle:"
echo "    docker pull image             Download image"
echo "    docker run -d --name c1 image Run container"
echo "    docker ps                     List running"
echo "    docker ps -a                  List all (inc stopped)"
echo "    docker stop c1                Graceful stop"
echo "    docker start c1               Start stopped"
echo "    docker restart c1             Restart"
echo "    docker rm c1                  Remove stopped"
echo "    docker rm -f c1               Force remove running"
echo ""
echo "  Inspect and debug:"
echo "    docker logs c1                View output"
echo "    docker logs -f c1             Follow output"
echo "    docker exec -it c1 sh         Shell into container"
echo "    docker inspect c1             Full details (JSON)"
echo "    docker top c1                 Processes in container"
echo "    docker stats                  Live resource usage"
echo ""
echo "  Images:"
echo "    docker images                 List local images"
echo "    docker rmi image              Remove image"
echo "    docker build -t name .        Build from Dockerfile"
echo "    docker tag image name:tag     Tag an image"
echo "    docker push name:tag          Push to registry"
echo "    docker image prune            Remove unused images"
echo ""
echo "  Volumes (persistent data):"
echo "    -v /host:/container           Bind mount"
echo "    -v /host:/container:ro        Read-only mount"
echo "    docker volume create name     Named volume"
echo "    docker volume ls              List volumes"
echo "    docker volume rm name         Remove volume"
echo ""
echo "  Networking:"
echo "    -p 8080:80                    Map host:container port"
echo "    docker network ls             List networks"
echo "    docker network create name    Create network"
echo "    --network name                Connect to network"
echo ""
echo "  Cleanup:"
echo "    docker system prune           Remove all unused"
echo "    docker container prune        Remove stopped"
echo "    docker image prune            Remove dangling images"

echo ""
echo "=== DOCKERFILE ==="
echo ""
echo "  Instructions:"
echo "    FROM ubuntu:24.04             Base image"
echo "    RUN apt update && apt install -y nginx"
echo "    COPY app/ /var/www/html/      Copy files in"
echo "    WORKDIR /app                  Set working directory"
echo "    EXPOSE 80                     Document port"
echo "    ENV NODE_ENV=production       Set variable"
echo "    USER appuser                  Run as non-root"
echo "    CMD [\"nginx\", \"-g\", \"daemon off;\"]  Default command"
echo "    ENTRYPOINT [\"/app/start.sh\"]  Cannot be overridden"
echo ""
echo "  CMD vs ENTRYPOINT:"
echo "    CMD = default command (can be overridden)"
echo "    ENTRYPOINT = always runs (CMD becomes arguments)"

echo ""
echo "=== PODMAN (Docker alternative) ==="
echo ""
echo "  Same commands as Docker but:"
echo "    - No daemon (daemonless)"
echo "    - Runs rootless by default"
echo "    - Drop-in replacement for Docker"
echo ""
echo "  podman run -d --name c1 nginx"
echo "  podman ps"
echo "  podman stop c1"
echo ""
echo "  Exam may ask about podman vs docker differences"
echo "  Key: podman = no daemon, rootless"

echo ""
echo "=== LINUX CONTAINER TECHNOLOGY ==="
echo ""
echo "  Namespaces (isolation):"
echo "    PID    Process isolation (container sees own PIDs)"
echo "    NET    Network isolation (own IP, ports)"
echo "    MNT    Mount isolation (own filesystem view)"
echo "    UTS    Hostname isolation"
echo "    IPC    Inter-process communication isolation"
echo "    USER   User ID isolation"
echo ""
echo "  cgroups (resource limits):"
echo "    CPU     Limit CPU usage"
echo "    Memory  Limit RAM usage"
echo "    I/O     Limit disk read/write"
echo "    PIDs    Limit number of processes"
echo ""
echo "  Namespaces = what you can SEE"
echo "  cgroups = what you can USE"

echo ""
echo "Containers and virtualization reference complete."
