#!/bin/bash
echo "================================================"
echo "  Cron Scheduling Reference"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "--- CRON FORMAT ---"
echo "  MIN  HOUR  DOM  MON  DOW  command"
echo "  0-59 0-23  1-31 1-12 0-7"
echo ""
echo "  DOW: 0 and 7 = Sunday, 1 = Monday ... 6 = Saturday"

echo ""
echo "--- EXAMPLES ---"
echo "  0 1 * * *        Every day at 1:00 AM"
echo "  */5 * * * *      Every 5 minutes"
echo "  0 */4 * * *      Every 4 hours"
echo "  30 8 * * 1-5     8:30 AM weekdays only"
echo "  0 0 1 * *        Midnight on the 1st of each month"
echo "  0 0 * * 0        Midnight every Sunday"
echo "  0 9,17 * * *     9 AM and 5 PM daily"
echo "  15 14 1 * *      2:15 PM on the 1st of each month"

echo ""
echo "--- CRON COMMANDS ---"
echo "  crontab -l       List current user's cron jobs"
echo "  crontab -e       Edit current user's cron jobs"
echo "  crontab -r       Remove ALL cron jobs (careful!)"
echo "  crontab -u user -l   List another user's cron jobs"

echo ""
echo "--- CRON DIRECTORIES ---"
echo "  /etc/crontab         System crontab"
echo "  /etc/cron.d/         Drop-in cron files"
echo "  /etc/cron.daily/     Scripts run daily"
echo "  /etc/cron.weekly/    Scripts run weekly"
echo "  /etc/cron.monthly/   Scripts run monthly"
echo "  /etc/cron.hourly/    Scripts run hourly"

echo ""
echo "--- AT COMMAND (one-time) ---"
echo "  at now + 30 minutes     Run once in 30 min"
echo "  at 2:00 AM tomorrow     Run at 2 AM tomorrow"
echo "  at now + 2 hours        Run in 2 hours"
echo "  atq                     List pending at jobs"
echo "  atrm <job#>             Remove an at job"

echo ""
echo "--- ACCESS CONTROL ---"
echo "  /etc/cron.allow    Users allowed to use cron"
echo "  /etc/cron.deny     Users denied from using cron"
echo "  /etc/at.allow      Users allowed to use at"
echo "  /etc/at.deny       Users denied from using at"
echo ""
echo "  If cron.allow exists, ONLY listed users can use cron"
echo "  If only cron.deny exists, everyone EXCEPT listed can use"
echo "  If neither exists, only root can use cron"

echo ""
echo "--- SYSTEMD TIMERS (modern alternative) ---"
echo "  systemctl list-timers          List active timers"
echo "  systemctl status <name>.timer  Check timer status"
echo "  /etc/systemd/system/<name>.timer   Timer unit file"
echo ""
echo "  Timers are replacing cron in modern systemd distros"
echo "  but cron is still heavily tested on Linux+"

echo ""
echo "Cron guide complete."
