#!/bin/bash
echo "================================================"
echo "  BUG FIX #5: Network Service Configuration"
echo "  Root Cause: Domain 2 - service configuration"
echo "  Fix Target: DNS, DHCP, email, print services"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== ROOT CAUSE ANALYSIS ==="
echo ""
echo "  Symptom: Domain 2 includes configuring common"
echo "  network services, not just managing systemd."
echo "  Questions test config file locations, key"
echo "  directives, and which service does what."

echo ""
echo "=== DNS SERVER (BIND) ==="
echo ""
echo "  Package: bind / bind9 / named"
echo "  Service: named (RHEL) / bind9 (Debian)"
echo "  Config: /etc/named.conf (RHEL)"
echo "  Config: /etc/bind/named.conf (Debian)"
echo "  Zone files: /var/named/ (RHEL)"
echo "  Zone files: /var/cache/bind/ (Debian)"
echo ""
echo "  Zone file record types:"
echo "    A       hostname -> IPv4 address"
echo "    AAAA    hostname -> IPv6 address"
echo "    CNAME   alias -> canonical name"
echo "    MX      domain -> mail server"
echo "    NS      domain -> nameserver"
echo "    PTR     IP -> hostname (reverse)"
echo "    SOA     start of authority (zone metadata)"
echo "    TXT     text record (SPF, DKIM, verification)"
echo "    SRV     service location (port, priority)"
echo ""
echo "  Exam tests: which record type for which purpose"
echo "  MX = email, A = website, PTR = reverse, CNAME = alias"

echo ""
echo "=== DHCP SERVER ==="
echo ""
echo "  Package: dhcp-server (RHEL) / isc-dhcp-server (Debian)"
echo "  Config: /etc/dhcp/dhcpd.conf"
echo ""
echo "  Key config directives:"
echo "    subnet 10.0.50.0 netmask 255.255.255.0 {"
echo "        range 10.0.50.100 10.0.50.200;"
echo "        option routers 10.0.50.1;"
echo "        option domain-name-servers 8.8.8.8;"
echo "        default-lease-time 3600;"
echo "        max-lease-time 7200;"
echo "    }"
echo ""
echo "  Static assignment (MAC -> IP):"
echo "    host printer {"
echo "        hardware ethernet 00:11:22:33:44:55;"
echo "        fixed-address 10.0.50.50;"
echo "    }"
echo ""
echo "  Lease file: /var/lib/dhcpd/dhcpd.leases"
echo "  Shows all active DHCP leases"

echo ""
echo "=== EMAIL SERVICES ==="
echo ""
echo "  Sending mail (MTA - Mail Transfer Agent):"
echo "    Postfix      Config: /etc/postfix/main.cf"
echo "    Sendmail     Config: /etc/mail/sendmail.cf"
echo "    Postfix is the modern standard"
echo ""
echo "  Receiving mail:"
echo "    Dovecot      IMAP/POP3 server"
echo "    Config: /etc/dovecot/dovecot.conf"
echo ""
echo "  Mail commands:"
echo "    mail -s 'Subject' user@domain < body.txt"
echo "    mailq                         View mail queue"
echo "    postqueue -p                  Postfix queue"
echo "    postfix check                 Verify config"
echo ""
echo "  Ports:"
echo "    25   SMTP (sending between servers)"
echo "    587  SMTP submission (clients to server)"
echo "    110  POP3 (retrieve, delete from server)"
echo "    143  IMAP (retrieve, keep on server)"
echo "    993  IMAPS (IMAP + TLS)"
echo "    995  POP3S (POP3 + TLS)"

echo ""
echo "=== PRINT SERVICES (CUPS) ==="
echo ""
echo "  Service: cups"
echo "  Config: /etc/cups/cupsd.conf"
echo "  Web interface: http://localhost:631"
echo ""
echo "  Commands:"
echo "    lpstat -p                     List printers"
echo "    lpstat -a                     Accepting jobs?"
echo "    lp -d printer file.pdf        Print a file"
echo "    lpr file.pdf                  Print (BSD style)"
echo "    lpq                           View print queue"
echo "    lprm job_id                   Cancel print job"
echo "    cupsctl                       Manage CUPS settings"
echo "    lpadmin -p name -E -v uri     Add a printer"
echo ""
echo "  Print protocols:"
echo "    IPP    Internet Printing Protocol (modern, port 631)"
echo "    LPD    Line Printer Daemon (legacy, port 515)"

echo ""
echo "=== PROXY AND CACHE ==="
echo ""
echo "  Squid:"
echo "    Forward proxy and web cache"
echo "    Config: /etc/squid/squid.conf"
echo "    Port: 3128 (default)"
echo ""
echo "  HAProxy:"
echo "    Load balancer and reverse proxy"
echo "    Config: /etc/haproxy/haproxy.cfg"
echo ""
echo "  Forward proxy: clients -> proxy -> internet"
echo "  Reverse proxy: internet -> proxy -> servers"

echo ""
echo "=== EXAM SCENARIOS ==="
echo ""
echo "  Q: Which record directs email for a domain?"
echo "  A: MX record"
echo ""
echo "  Q: Where are DHCP leases stored?"
echo "  A: /var/lib/dhcpd/dhcpd.leases"
echo ""
echo "  Q: Which port does CUPS listen on?"
echo "  A: 631"
echo ""
echo "  Q: Difference between IMAP and POP3?"
echo "  A: IMAP keeps mail on server, POP3 downloads and deletes"
echo ""
echo "  Q: Which service is a Mail Transfer Agent?"
echo "  A: Postfix or Sendmail (not Dovecot)"

echo ""
echo "Bug fix #5 complete."
