#!/bin/bash
echo "================================================"
echo "  BUG FIX #9: SELinux Port and Service Contexts"
echo "  Root Cause: Domain 1/2 crossover"
echo "  Fix Target: When services use non-standard ports"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== ROOT CAUSE ANALYSIS ==="
echo ""
echo "  Symptom: You know SELinux file contexts (Scenario 7)"
echo "  but the exam also tests PORT contexts and booleans"
echo "  for service configuration. A web server on port 8080"
echo "  or SSH on port 2222 gets blocked by SELinux even"
echo "  with correct file permissions."

echo ""
echo "=== PORT CONTEXTS ==="
echo ""
echo "  SELinux controls which ports a service can use"
echo ""
echo "  View allowed ports for a type:"
echo "    semanage port -l | grep http"
echo "    http_port_t     tcp   80, 81, 443, 488, 8008, 8009, 8443, 9000"
echo ""
echo "  Problem: Nginx configured on port 8080"
echo "  SELinux: 8080 not in http_port_t -> BLOCKED"
echo ""
echo "  Fix: Add port to the SELinux type"
echo "    semanage port -a -t http_port_t -p tcp 8080"
echo ""
echo "  Flags:"
echo "    -a = add"
echo "    -t = type"
echo "    -p = protocol (tcp/udp)"
echo ""
echo "  Problem: SSH moved to port 2222"
echo "    semanage port -a -t ssh_port_t -p tcp 2222"
echo ""
echo "  List all port assignments:"
echo "    semanage port -l"
echo ""
echo "  Modify existing:"
echo "    semanage port -m -t http_port_t -p tcp 8080"
echo ""
echo "  Delete:"
echo "    semanage port -d -t http_port_t -p tcp 8080"

echo ""
echo "=== COMMON PORT TYPES ==="
echo ""
echo "  http_port_t        Web servers (80, 443, 8080)"
echo "  ssh_port_t         SSH (22)"
echo "  smtp_port_t        Mail (25, 587)"
echo "  mysqld_port_t      MySQL (3306)"
echo "  postgresql_port_t  PostgreSQL (5432)"
echo "  dns_port_t         DNS (53)"
echo "  ntp_port_t         NTP (123)"

echo ""
echo "=== BOOLEANS DEEP DIVE ==="
echo ""
echo "  Booleans are on/off switches for SELinux policies"
echo "  They enable specific behaviors without rewriting policy"
echo ""
echo "  List all booleans:"
echo "    getsebool -a"
echo "    getsebool -a | wc -l              Count (300+)"
echo ""
echo "  Search for specific:"
echo "    getsebool -a | grep httpd"
echo ""
echo "  Common httpd booleans:"
echo "    httpd_can_network_connect = off"
echo "      Allow web server to make outbound connections"
echo "      Need this for: proxy, API calls, DB connections"
echo ""
echo "    httpd_can_network_connect_db = off"
echo "      Allow web server to connect to databases"
echo "      More specific than network_connect"
echo ""
echo "    httpd_enable_homedirs = off"
echo "      Allow web server to serve user home directories"
echo "      ~user/ URLs"
echo ""
echo "    httpd_can_sendmail = off"
echo "      Allow web server to send emails"
echo ""
echo "    httpd_use_nfs = off"
echo "      Allow web server to access NFS mounts"
echo ""
echo "  Common other booleans:"
echo "    ftpd_anon_write = off"
echo "      Allow anonymous FTP uploads"
echo ""
echo "    samba_enable_home_dirs = off"
echo "      Allow Samba to share home directories"
echo ""
echo "    ssh_sysadm_login = off"
echo "      Allow sysadm_u to SSH in"

echo ""
echo "  Set boolean temporarily:"
echo "    setsebool httpd_can_network_connect on"
echo ""
echo "  Set boolean permanently:"
echo "    setsebool -P httpd_can_network_connect on"
echo ""
echo "  CRITICAL: -P = Persistent (survives reboot)"
echo "  Without -P, it reverts on reboot"

echo ""
echo "=== COMPLETE SELINUX TROUBLESHOOTING FLOW ==="
echo ""
echo "  1. Service fails or access denied"
echo "  2. Check audit log:"
echo "     ausearch -m avc -ts recent"
echo "  3. Get human-readable explanation:"
echo "     sealert -a /var/log/audit/audit.log"
echo "  4. Identify the issue type:"
echo "     a) Wrong FILE context -> restorecon"
echo "     b) Wrong PORT -> semanage port -a"
echo "     c) Missing BOOLEAN -> setsebool -P"
echo "  5. Apply fix"
echo "  6. Verify: restart service, test access"
echo ""
echo "  NEVER setenforce 0 as a fix"
echo "  NEVER disable SELinux"
echo "  Always fix the specific context, port, or boolean"

echo ""
echo "=== EXAM SCENARIOS ==="
echo ""
echo "  Q: Apache on port 8080 won't start, SELinux enforcing"
echo "  A: semanage port -a -t http_port_t -p tcp 8080"
echo ""
echo "  Q: Web app can't connect to database, SELinux audit shows deny"
echo "  A: setsebool -P httpd_can_network_connect_db on"
echo ""
echo "  Q: SSH on port 2222, connections refused"
echo "  A: semanage port -a -t ssh_port_t -p tcp 2222"
echo "     AND firewall-cmd --add-port=2222/tcp --permanent"

echo ""
echo "Bug fix #9 complete."
