#!/bin/bash
echo "================================================"
echo "  BUG FIX #2: Service Types and Socket Activation"
echo "  Root Cause: Domain 2 Services confusion"
echo "  Fix Target: Type= directive and socket units"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== ROOT CAUSE ANALYSIS ==="
echo ""
echo "  Symptom: Questions about how systemd knows a"
echo "  service is 'ready' and how services activate"
echo "  on demand. The Type= directive controls this"
echo "  and each type has different behavior."

echo ""
echo "=== THE FIX: SERVICE TYPES DEEP DIVE ==="
echo ""
echo "  Type=simple (DEFAULT)"
echo "  ---"
echo "  Process started by ExecStart IS the service"
echo "  systemd considers it 'started' immediately"
echo "  Process must NOT fork to background"
echo "  If process exits, service is considered stopped"
echo ""
echo "  Example: Node.js, Python apps, nginx (foreground)"
echo "  ExecStart=/usr/bin/node /opt/app/server.js"

echo ""
echo "  Type=forking"
echo "  ---"
echo "  Process started by ExecStart forks a child"
echo "  Parent exits, child continues in background"
echo "  systemd waits for parent to exit = 'started'"
echo "  Must specify PIDFile= so systemd tracks the child"
echo ""
echo "  Example: Apache httpd, traditional daemons"
echo "  ExecStart=/usr/sbin/httpd -DFOREGROUND"
echo "  PIDFile=/run/httpd/httpd.pid"

echo ""
echo "  Type=oneshot"
echo "  ---"
echo "  Process runs once and exits"
echo "  systemd waits for it to FINISH before 'started'"
echo "  Good for initialization scripts"
echo "  Often paired with RemainAfterExit=yes"
echo ""
echo "  Example: Firewall rules, database migration"
echo "  ExecStart=/opt/scripts/init-firewall.sh"
echo "  RemainAfterExit=yes"
echo ""
echo "  RemainAfterExit=yes means:"
echo "    Service shows as 'active' even after process exits"
echo "    Without it, service shows 'inactive' after script finishes"

echo ""
echo "  Type=notify"
echo "  ---"
echo "  Like simple, but process tells systemd when ready"
echo "  Uses sd_notify() function to signal readiness"
echo "  systemd waits for the notification before 'started'"
echo "  More accurate startup detection than simple"
echo ""
echo "  Example: PostgreSQL, systemd-resolved"

echo ""
echo "  Type=idle"
echo "  ---"
echo "  Like simple, but waits until all other jobs finish"
echo "  Used for services that should start last"
echo "  Prevents console output mixing with boot messages"

echo ""
echo "=== SOCKET ACTIVATION ==="
echo ""
echo "  Instead of running a service constantly,"
echo "  systemd listens on a socket and starts the"
echo "  service only when a connection arrives."
echo ""
echo "  Two unit files needed:"
echo ""
echo "  1. myapp.socket"
echo "  [Socket]"
echo "  ListenStream=8080"
echo "  Accept=no"
echo ""
echo "  [Install]"
echo "  WantedBy=sockets.target"
echo ""
echo "  2. myapp.service"
echo "  [Service]"
echo "  ExecStart=/opt/myapp/bin/server"
echo ""
echo "  How it works:"
echo "    1. systemd listens on port 8080"
echo "    2. Nothing is running, zero resources used"
echo "    3. Client connects to port 8080"
echo "    4. systemd starts myapp.service"
echo "    5. Hands the connection to the service"
echo "    6. Service handles the request"
echo ""
echo "  Benefits:"
echo "    - Services start on demand (save resources)"
echo "    - Parallel boot (sockets ready before services)"
echo "    - Automatic restart on crash"
echo ""
echo "  Commands:"
echo "    systemctl list-sockets          List all sockets"
echo "    systemctl start myapp.socket    Enable socket listening"
echo "    systemctl status myapp.socket   Check socket status"

echo ""
echo "=== EXAM SCENARIOS ==="
echo ""
echo "  Q: Service forks to background, systemd loses track"
echo "  A: Change Type=simple to Type=forking, add PIDFile="
echo ""
echo "  Q: Init script should run once at boot and show active"
echo "  A: Type=oneshot with RemainAfterExit=yes"
echo ""
echo "  Q: Service should only start when client connects"
echo "  A: Create a .socket unit with socket activation"
echo ""
echo "  Q: Service reports started before it's actually ready"
echo "  A: Change to Type=notify if app supports sd_notify"

echo ""
echo "Bug fix #2 complete."
