#!/bin/bash
echo "================================================"
echo "  BUG FIX #6: Software RAID (mdadm)"
echo "  Root Cause: Domain 1 flat at 71%"
echo "  Fix Target: RAID levels and mdadm commands"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== ROOT CAUSE ANALYSIS ==="
echo ""
echo "  Symptom: Domain 1 System Management hasn't moved."
echo "  RAID is a storage topic that shows up consistently."
echo "  Need to know RAID levels, trade-offs, and mdadm."

echo ""
echo "=== RAID LEVELS (must memorize) ==="
echo ""
echo "  RAID 0 - Striping"
echo "    Min disks: 2"
echo "    Redundancy: NONE"
echo "    Performance: Fastest read and write"
echo "    Capacity: 100% (all disks combined)"
echo "    Risk: ONE disk fails = ALL data lost"
echo "    Use: Temp data, caches, speed over safety"
echo ""
echo "  RAID 1 - Mirroring"
echo "    Min disks: 2"
echo "    Redundancy: Full copy on each disk"
echo "    Performance: Fast reads, normal writes"
echo "    Capacity: 50% (half is mirrors)"
echo "    Risk: Can lose 1 disk and survive"
echo "    Use: Boot drives, critical small volumes"
echo ""
echo "  RAID 5 - Striping with Distributed Parity"
echo "    Min disks: 3"
echo "    Redundancy: One disk worth of parity"
echo "    Performance: Good reads, slower writes"
echo "    Capacity: (N-1) disks"
echo "    Risk: Can lose 1 disk and survive"
echo "    Use: General purpose, balanced"
echo ""
echo "  RAID 6 - Striping with Double Parity"
echo "    Min disks: 4"
echo "    Redundancy: Two disks worth of parity"
echo "    Performance: Good reads, slower writes"
echo "    Capacity: (N-2) disks"
echo "    Risk: Can lose 2 disks and survive"
echo "    Use: Large arrays, extra safety"
echo ""
echo "  RAID 10 (1+0) - Mirrored Stripes"
echo "    Min disks: 4"
echo "    Redundancy: Mirrored pairs"
echo "    Performance: Fastest with redundancy"
echo "    Capacity: 50%"
echo "    Risk: Can lose 1 disk per mirror pair"
echo "    Use: Databases, high-performance + safety"

echo ""
echo "=== QUICK COMPARISON ==="
echo ""
echo "  Level  Min  Capacity  Survive   Speed    Use Case"
echo "  -----  ---  --------  -------   -----    --------"
echo "  0      2    100%      0 disks   Fastest  Temp/cache"
echo "  1      2    50%       1 disk    Fast R   Boot/OS"
echo "  5      3    N-1       1 disk    Good     General"
echo "  6      4    N-2       2 disks   Good     Large arrays"
echo "  10     4    50%       1/pair    Fastest  Databases"

echo ""
echo "=== MDADM COMMANDS ==="
echo ""
echo "  Create RAID array:"
echo "    mdadm --create /dev/md0 --level=1 --raid-devices=2 /dev/sdb /dev/sdc"
echo ""
echo "  Breakdown:"
echo "    --create /dev/md0     Create array named md0"
echo "    --level=1             RAID level 1 (mirror)"
echo "    --raid-devices=2      Number of disks"
echo "    /dev/sdb /dev/sdc     The actual disks"
echo ""
echo "  Check array status:"
echo "    cat /proc/mdstat              Quick status"
echo "    mdadm --detail /dev/md0       Detailed info"
echo "    mdadm --examine /dev/sdb      Examine member disk"
echo ""
echo "  Add spare disk:"
echo "    mdadm --manage /dev/md0 --add /dev/sdd"
echo ""
echo "  Remove failed disk:"
echo "    mdadm --manage /dev/md0 --fail /dev/sdc"
echo "    mdadm --manage /dev/md0 --remove /dev/sdc"
echo ""
echo "  Stop and destroy:"
echo "    mdadm --stop /dev/md0"
echo "    mdadm --zero-superblock /dev/sdb /dev/sdc"
echo ""
echo "  Save config (persistent across reboot):"
echo "    mdadm --detail --scan >> /etc/mdadm/mdadm.conf"
echo "    update-initramfs -u       (Debian)"
echo "    dracut --force             (RHEL)"

echo ""
echo "=== AFTER CREATING RAID ==="
echo ""
echo "  The RAID array acts like a single disk:"
echo "    mkfs.ext4 /dev/md0           Create filesystem"
echo "    mkdir /data"
echo "    mount /dev/md0 /data         Mount it"
echo ""
echo "  Add to fstab for persistence:"
echo "    /dev/md0  /data  ext4  defaults  0  2"

echo ""
echo "=== EXAM SCENARIOS ==="
echo ""
echo "  Q: Need fast storage, no redundancy needed"
echo "  A: RAID 0"
echo ""
echo "  Q: Database needs speed AND redundancy"
echo "  A: RAID 10"
echo ""
echo "  Q: 4 disks, need to survive 2 failures"
echo "  A: RAID 6"
echo ""
echo "  Q: How many usable disks in 5-disk RAID 5?"
echo "  A: 4 (N-1)"
echo ""
echo "  Q: Where to check RAID build progress?"
echo "  A: cat /proc/mdstat"

echo ""
echo "Bug fix #6 complete."
