#!/bin/bash
echo "================================================"
echo "  BUG FIX #7: Package Management Across Distros"
echo "  Root Cause: Domain 1 flat at 71%"
echo "  Fix Target: apt vs dnf vs zypper vs rpm vs dpkg"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== ROOT CAUSE ANALYSIS ==="
echo ""
echo "  Symptom: Questions give a scenario on a specific"
echo "  distro and ask which command to use. Must know"
echo "  the package tool for each distro family AND the"
echo "  low-level vs high-level distinction."

echo ""
echo "=== DISTRO FAMILIES ==="
echo ""
echo "  Debian Family (Ubuntu, Mint, Kali):"
echo "    Package format: .deb"
echo "    Low-level tool: dpkg"
echo "    High-level tool: apt / apt-get"
echo ""
echo "  RHEL Family (CentOS, Rocky, Alma, Fedora):"
echo "    Package format: .rpm"
echo "    Low-level tool: rpm"
echo "    High-level tool: dnf (yum is legacy)"
echo ""
echo "  SUSE Family (openSUSE, SLES):"
echo "    Package format: .rpm"
echo "    Low-level tool: rpm"
echo "    High-level tool: zypper"
echo ""
echo "  Low-level = install a local file, no dependencies"
echo "  High-level = resolve dependencies, download from repos"

echo ""
echo "=== APT (Debian/Ubuntu) ==="
echo ""
echo "  apt update                    Refresh package list"
echo "  apt upgrade                   Upgrade all packages"
echo "  apt full-upgrade              Upgrade + remove obsolete"
echo "  apt install nginx             Install package"
echo "  apt remove nginx              Remove (keep config)"
echo "  apt purge nginx               Remove + delete config"
echo "  apt autoremove                Remove unused dependencies"
echo "  apt search nginx              Search for package"
echo "  apt show nginx                Package details"
echo "  apt list --installed          List installed packages"
echo "  apt list --upgradable         List available upgrades"
echo ""
echo "  Repo config: /etc/apt/sources.list"
echo "  Repo drop-ins: /etc/apt/sources.list.d/"
echo "  Cache: /var/cache/apt/archives/"

echo ""
echo "=== DPKG (Debian low-level) ==="
echo ""
echo "  dpkg -i package.deb           Install local .deb file"
echo "  dpkg -r package               Remove package"
echo "  dpkg -P package               Purge (remove + config)"
echo "  dpkg -l                        List all installed"
echo "  dpkg -l nginx                  Check if installed"
echo "  dpkg -L nginx                  List files in package"
echo "  dpkg -S /usr/bin/nginx         Which package owns file?"
echo "  dpkg --configure -a            Fix interrupted installs"
echo ""
echo "  dpkg does NOT resolve dependencies"
echo "  If dependency is missing, install fails"

echo ""
echo "=== DNF (RHEL/CentOS/Fedora) ==="
echo ""
echo "  dnf install nginx              Install"
echo "  dnf remove nginx               Remove"
echo "  dnf update                     Update all packages"
echo "  dnf update nginx               Update specific package"
echo "  dnf search nginx               Search"
echo "  dnf info nginx                 Package details"
echo "  dnf list installed             List installed"
echo "  dnf list available             List available"
echo "  dnf provides /usr/bin/nginx    Which package has file?"
echo "  dnf history                    Transaction history"
echo "  dnf history undo 15            Undo transaction 15"
echo "  dnf clean all                  Clear cache"
echo "  dnf repolist                   List enabled repos"
echo "  dnf group install 'Server'     Install package group"
echo ""
echo "  Repo config: /etc/yum.repos.d/*.repo"
echo ""
echo "  YUM is legacy, DNF is current"
echo "  yum commands still work (symlinked to dnf)"

echo ""
echo "=== RPM (RHEL low-level) ==="
echo ""
echo "  rpm -ivh package.rpm           Install local .rpm"
echo "  rpm -Uvh package.rpm           Upgrade (or install)"
echo "  rpm -e package                 Remove"
echo "  rpm -qa                        List all installed"
echo "  rpm -qi nginx                  Package info"
echo "  rpm -ql nginx                  List files in package"
echo "  rpm -qf /usr/bin/nginx         Which package owns file?"
echo "  rpm -qR nginx                  List dependencies"
echo "  rpm -V nginx                   Verify package integrity"
echo ""
echo "  Flags: i=install U=upgrade e=erase q=query"
echo "         v=verbose h=hash progress"
echo "         a=all l=list f=file R=requires"

echo ""
echo "=== ZYPPER (SUSE) ==="
echo ""
echo "  zypper install nginx           Install"
echo "  zypper remove nginx            Remove"
echo "  zypper update                  Update all"
echo "  zypper search nginx            Search"
echo "  zypper info nginx              Package info"
echo "  zypper refresh                 Refresh repos"
echo "  zypper repos                   List repos"
echo "  zypper patches                 List patches"

echo ""
echo "=== EXAM DECISION TREE ==="
echo ""
echo "  Scenario mentions Ubuntu/Debian:"
echo "    Install from repo -> apt install"
echo "    Install local file -> dpkg -i"
echo "    What files in package -> dpkg -L"
echo "    Which package owns file -> dpkg -S"
echo ""
echo "  Scenario mentions RHEL/CentOS/Fedora:"
echo "    Install from repo -> dnf install"
echo "    Install local file -> rpm -ivh"
echo "    What files in package -> rpm -ql"
echo "    Which package owns file -> rpm -qf / dnf provides"
echo ""
echo "  Scenario mentions SUSE:"
echo "    Use zypper for everything high-level"
echo "    Use rpm for low-level"

echo ""
echo "Bug fix #7 complete."
