#!/bin/bash
echo "================================================"
echo "  BUG FIX #3: Systemd Timers"
echo "  Root Cause: Domain 2 - modern scheduling"
echo "  Fix Target: Timer units replacing cron"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== ROOT CAUSE ANALYSIS ==="
echo ""
echo "  Symptom: Exam asks about scheduling with systemd"
echo "  not just cron. Timer units are the modern way"
echo "  and questions test the difference."

echo ""
echo "=== THE FIX: TIMER UNITS ==="
echo ""
echo "  Two files needed (like socket activation):"
echo ""
echo "  1. backup.timer (WHEN to run)"
echo "  ----------------------------------------"
echo "  [Unit]"
echo "  Description=Daily Backup Timer"
echo ""
echo "  [Timer]"
echo "  OnCalendar=*-*-* 01:00:00"
echo "  Persistent=true"
echo "  RandomizedDelaySec=300"
echo ""
echo "  [Install]"
echo "  WantedBy=timers.target"
echo "  ----------------------------------------"
echo ""
echo "  2. backup.service (WHAT to run)"
echo "  ----------------------------------------"
echo "  [Unit]"
echo "  Description=Daily Backup Job"
echo ""
echo "  [Service]"
echo "  Type=oneshot"
echo "  ExecStart=/opt/scripts/backup.sh"
echo "  ----------------------------------------"
echo ""
echo "  Timer and service must have the SAME name"
echo "  backup.timer triggers backup.service automatically"

echo ""
echo "=== ONCALENDAR FORMAT ==="
echo ""
echo "  Format: DayOfWeek Year-Month-Day Hour:Minute:Second"
echo ""
echo "  Examples:"
echo "    *-*-* 01:00:00          Daily at 1 AM"
echo "    Mon *-*-* 09:00:00      Every Monday at 9 AM"
echo "    *-*-01 00:00:00         First of every month"
echo "    *-*-* *:*:00            Every minute"
echo "    *-*-* 00/4:00:00        Every 4 hours"
echo "    Sat,Sun *-*-* 10:00:00  Weekends at 10 AM"
echo "    *-01,07-01 00:00:00     Jan 1 and Jul 1"
echo ""
echo "  Shortcuts:"
echo "    hourly       = *-*-* *:00:00"
echo "    daily        = *-*-* 00:00:00"
echo "    weekly       = Mon *-*-* 00:00:00"
echo "    monthly      = *-*-01 00:00:00"
echo ""
echo "  Test your schedule:"
echo "    systemd-analyze calendar 'Mon *-*-* 09:00:00'"
echo "    Shows next trigger times"

echo ""
echo "=== MONOTONIC TIMERS (relative time) ==="
echo ""
echo "  Instead of calendar time, run relative to events:"
echo ""
echo "  OnBootSec=15min           15 min after boot"
echo "  OnUnitActiveSec=1h        1 hour after service last ran"
echo "  OnStartupSec=5min         5 min after systemd started"
echo "  OnActiveSec=30s           30 sec after timer activated"
echo ""
echo "  Use case: retry a service every 10 minutes"
echo "  [Timer]"
echo "  OnUnitActiveSec=10min"
echo "  OnBootSec=5min"

echo ""
echo "=== TIMER DIRECTIVES ==="
echo ""
echo "  Persistent=true"
echo "    If system was off when timer should have fired,"
echo "    run the job immediately on next boot"
echo "    Like anacron for cron jobs"
echo ""
echo "  RandomizedDelaySec=300"
echo "    Add random 0-300 second delay"
echo "    Prevents all servers running backup at exact same time"
echo ""
echo "  AccuracySec=1min"
echo "    How precise the timer needs to be"
echo "    Default is 1 minute"

echo ""
echo "=== MANAGING TIMERS ==="
echo ""
echo "  systemctl enable backup.timer       Enable (start on boot)"
echo "  systemctl start backup.timer        Start now"
echo "  systemctl stop backup.timer         Stop"
echo "  systemctl status backup.timer       Check status"
echo "  systemctl list-timers               List all active timers"
echo "  systemctl list-timers --all         Include inactive"
echo ""
echo "  Output of list-timers shows:"
echo "    NEXT       = when it fires next"
echo "    LEFT       = time until next fire"
echo "    LAST       = when it last fired"
echo "    PASSED     = time since last fire"
echo "    UNIT       = timer unit name"
echo "    ACTIVATES  = service it triggers"

echo ""
echo "=== CRON vs TIMER COMPARISON ==="
echo ""
echo "  Feature           Cron            Timer"
echo "  --------          ----            -----"
echo "  Logging           Manual          journalctl -u"
echo "  Dependencies      None            Full systemd deps"
echo "  Missed runs       Lost (or anacron) Persistent=true"
echo "  Resource control  None            MemoryMax, CPUQuota"
echo "  Random delay      None            RandomizedDelaySec"
echo "  Centralized mgmt  crontab -l      systemctl list-timers"
echo "  Per-user          crontab -e      ~/.config/systemd/user/"
echo ""
echo "  Timers are replacing cron in modern distros"
echo "  Exam tests BOTH"

echo ""
echo "Bug fix #3 complete."
