#!/bin/bash
echo "================================================"
echo "  BUG FIX #8: Kernel Parameter Tuning (sysctl)"
echo "  Root Cause: Domain 1 flat at 71%"
echo "  Fix Target: Runtime kernel config and /proc/sys"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== ROOT CAUSE ANALYSIS ==="
echo ""
echo "  Symptom: Questions about modifying kernel behavior"
echo "  at runtime without rebooting. sysctl and /proc/sys"
echo "  are the mechanism. Must know common parameters."

echo ""
echo "=== SYSCTL BASICS ==="
echo ""
echo "  View all parameters:"
echo "    sysctl -a                        List everything"
echo "    sysctl -a | wc -l               Count (usually 1000+)"
echo ""
echo "  Read specific parameter:"
echo "    sysctl net.ipv4.ip_forward"
echo "    sysctl vm.swappiness"
echo "    sysctl kernel.hostname"
echo ""
echo "  Set temporarily (lost on reboot):"
echo "    sysctl -w net.ipv4.ip_forward=1"
echo "    sysctl -w vm.swappiness=10"
echo ""
echo "  Set permanently:"
echo "    Edit /etc/sysctl.conf or create file in /etc/sysctl.d/"
echo "    Then: sysctl -p         (reload config)"
echo ""
echo "  Alternative: write directly to /proc/sys"
echo "    echo 1 > /proc/sys/net/ipv4/ip_forward"
echo "    Same effect as sysctl -w, also temporary"

echo ""
echo "=== COMMON PARAMETERS (exam tested) ==="
echo ""
echo "  --- NETWORKING ---"
echo ""
echo "  net.ipv4.ip_forward = 1"
echo "    Enable IP forwarding (routing between interfaces)"
echo "    Required for: routers, NAT, containers, VPNs"
echo "    Default: 0 (disabled)"
echo ""
echo "  net.ipv4.icmp_echo_ignore_all = 1"
echo "    Ignore ping requests (security hardening)"
echo "    Default: 0 (respond to pings)"
echo ""
echo "  net.ipv4.tcp_syncookies = 1"
echo "    Protect against SYN flood attacks"
echo "    Default: 1 (enabled)"
echo ""
echo "  net.ipv4.conf.all.accept_redirects = 0"
echo "    Reject ICMP redirects (prevent MITM)"
echo "    Default: 1 on some distros"
echo ""
echo "  net.ipv4.conf.all.rp_filter = 1"
echo "    Reverse path filtering (anti-spoofing)"
echo "    Drops packets with impossible source IPs"

echo ""
echo "  --- MEMORY ---"
echo ""
echo "  vm.swappiness = 10"
echo "    How aggressively to use swap"
echo "    0 = avoid swap, 100 = swap eagerly"
echo "    Default: 60"
echo "    Servers: set to 10 (prefer RAM over swap)"
echo ""
echo "  vm.overcommit_memory = 0"
echo "    0 = estimate if enough memory (default)"
echo "    1 = always allow (dangerous)"
echo "    2 = never overcommit"
echo ""
echo "  vm.dirty_ratio = 20"
echo "    Percentage of RAM for dirty pages before sync"

echo ""
echo "  --- KERNEL ---"
echo ""
echo "  kernel.hostname = server01"
echo "    System hostname"
echo ""
echo "  kernel.panic = 10"
echo "    Reboot 10 seconds after kernel panic"
echo "    0 = don't auto reboot"
echo ""
echo "  kernel.sysrq = 0"
echo "    Disable magic SysRq key (security)"
echo "    1 = enable all SysRq functions"
echo ""
echo "  fs.file-max = 2097152"
echo "    Maximum number of file handles system-wide"

echo ""
echo "=== /proc/sys MAPPING ==="
echo ""
echo "  sysctl parameter dots = directory slashes in /proc"
echo ""
echo "  net.ipv4.ip_forward"
echo "  = /proc/sys/net/ipv4/ip_forward"
echo ""
echo "  vm.swappiness"
echo "  = /proc/sys/vm/swappiness"
echo ""
echo "  kernel.hostname"
echo "  = /proc/sys/kernel/hostname"
echo ""
echo "  The exam may show either format"

echo ""
echo "=== PERSISTENT CONFIGURATION ==="
echo ""
echo "  /etc/sysctl.conf               Main config file"
echo "  /etc/sysctl.d/*.conf           Drop-in files"
echo ""
echo "  Example /etc/sysctl.d/99-custom.conf:"
echo "    net.ipv4.ip_forward = 1"
echo "    vm.swappiness = 10"
echo "    net.ipv4.conf.all.accept_redirects = 0"
echo ""
echo "  Apply: sysctl -p /etc/sysctl.d/99-custom.conf"
echo "  Apply all: sysctl --system"

echo ""
echo "=== EXAM SCENARIOS ==="
echo ""
echo "  Q: Linux server needs to route between two networks"
echo "  A: sysctl -w net.ipv4.ip_forward=1"
echo ""
echo "  Q: Reduce swap usage on a database server"
echo "  A: sysctl -w vm.swappiness=10"
echo ""
echo "  Q: Make kernel changes persist across reboot"
echo "  A: Add to /etc/sysctl.conf, run sysctl -p"
echo ""
echo "  Q: Server should not respond to ping"
echo "  A: sysctl -w net.ipv4.icmp_echo_ignore_all=1"

echo ""
echo "Bug fix #8 complete."
