#!/bin/bash
echo "================================================"
echo "  BUG FIX #1: Systemd Dependency and Ordering"
echo "  Root Cause: Domain 2 dropped 78% -> 67%"
echo "  Fix Target: Service startup ordering"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== ROOT CAUSE ANALYSIS ==="
echo ""
echo "  Symptom: Missing questions about how services"
echo "  depend on each other and the order they start."
echo "  The exam tests the difference between Wants,"
echo "  Requires, After, Before, and BindsTo."
echo ""
echo "  These look similar but behave very differently"
echo "  under failure conditions."

echo ""
echo "=== THE FIX: DEPENDENCY DIRECTIVES ==="
echo ""
echo "  --- Ordering (WHEN to start) ---"
echo ""
echo "  After=network.target"
echo "    'Start my service AFTER network is ready'"
echo "    Does NOT create a dependency"
echo "    Just controls timing"
echo ""
echo "  Before=nginx.service"
echo "    'Start my service BEFORE nginx'"
echo "    Reverse of After"
echo "    Also just timing, no dependency"
echo ""
echo "  CRITICAL: After/Before only control ORDER"
echo "  They do NOT cause the other service to start"

echo ""
echo "  --- Dependencies (WHAT must be running) ---"
echo ""
echo "  Wants=postgresql.service"
echo "    'I want postgres running, but I'll start without it'"
echo "    Weak dependency"
echo "    If postgres fails to start, my service STILL starts"
echo "    Most common dependency type"
echo ""
echo "  Requires=postgresql.service"
echo "    'I NEED postgres running or I refuse to start'"
echo "    Strong dependency"
echo "    If postgres fails, my service fails too"
echo "    If postgres stops later, my service stops too"
echo ""
echo "  BindsTo=postgresql.service"
echo "    'My life is tied to postgres completely'"
echo "    Strongest dependency"
echo "    If postgres stops, restarts, or fails: I stop too"
echo "    Used for tightly coupled services"
echo ""
echo "  Requisite=postgresql.service"
echo "    'Postgres must ALREADY be running'"
echo "    Does not try to start postgres"
echo "    Fails immediately if postgres is not active"

echo ""
echo "  --- The Combo Pattern ---"
echo ""
echo "  Most real unit files use BOTH:"
echo ""
echo "  [Unit]"
echo "  After=network.target postgresql.service"
echo "  Wants=postgresql.service"
echo ""
echo "  Translation:"
echo "    After = start postgres first, then start me"
echo "    Wants = try to start postgres, but don't fail if it can't"
echo ""
echo "  Without After:"
echo "    Both services start simultaneously"
echo "    Race condition: your app might start before DB is ready"
echo ""
echo "  Without Wants:"
echo "    Your service starts after postgres IF postgres"
echo "    was already being started by something else"
echo "    But it won't trigger postgres to start"

echo ""
echo "=== EXAM SCENARIOS ==="
echo ""
echo "  Q: Service starts before its database is ready"
echo "  A: Missing After=database.service in unit file"
echo ""
echo "  Q: Service should start even if dependency is down"
echo "  A: Use Wants= (not Requires=)"
echo ""
echo "  Q: Service must stop when dependency stops"
echo "  A: Use BindsTo="
echo ""
echo "  Q: How to see what a service depends on?"
echo "  A: systemctl list-dependencies service_name"
echo ""
echo "  Q: How to see what depends ON a service?"
echo "  A: systemctl list-dependencies --reverse service_name"

echo ""
echo "=== EDGE CASES ==="
echo ""
echo "  Circular dependency:"
echo "    A wants B, B wants A"
echo "    systemd detects and logs a warning"
echo "    Both services attempt to start"
echo ""
echo "  Conditional dependencies:"
echo "    ConditionPathExists=/etc/app/config.yaml"
echo "    Service only starts if file exists"
echo "    No error if condition fails, just skips"
echo ""
echo "  AssertPathExists=/etc/app/config.yaml"
echo "    Same check but FAILS with error if missing"

echo ""
echo "Bug fix #1 complete."
