#!/bin/bash
echo "================================================"
echo "  BUG FIX #4: Disk Quota Management"
echo "  Root Cause: Domain 2 - user resource limits"
echo "  Fix Target: Quota setup and enforcement"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== ROOT CAUSE ANALYSIS ==="
echo ""
echo "  Symptom: Questions about user storage limits,"
echo "  the difference between hard/soft quotas, block"
echo "  vs inode quotas, and the grace period."

echo ""
echo "=== THE FIX: QUOTA TYPES ==="
echo ""
echo "  Two dimensions of quotas:"
echo ""
echo "  1. WHAT is being limited:"
echo "     Block quota = disk SPACE (KB, MB, GB)"
echo "     Inode quota = number of FILES"
echo ""
echo "  2. HOW strictly:"
echo "     Soft limit = warning threshold (can exceed temporarily)"
echo "     Hard limit = absolute ceiling (cannot exceed ever)"
echo ""
echo "  The matrix:"
echo "    Block soft  = 'You're using a lot of space' (warning)"
echo "    Block hard  = 'You cannot write any more data' (blocked)"
echo "    Inode soft  = 'You have a lot of files' (warning)"
echo "    Inode hard  = 'You cannot create any more files' (blocked)"

echo ""
echo "=== GRACE PERIOD ==="
echo ""
echo "  When you exceed the SOFT limit:"
echo "    A timer starts (default: 7 days)"
echo "    During grace period: you can still write"
echo "    After grace period expires: soft limit becomes hard"
echo "    You MUST reduce below soft limit to reset"
echo ""
echo "  Grace period only applies to soft limits"
echo "  Hard limits have NO grace period - instant block"

echo ""
echo "=== SETTING UP QUOTAS ==="
echo ""
echo "  Step 1: Enable quotas in fstab"
echo "    /dev/sda1 /home ext4 defaults,usrquota,grpquota 0 2"
echo ""
echo "    usrquota = enable per-user quotas"
echo "    grpquota = enable per-group quotas"
echo ""
echo "  Step 2: Remount the filesystem"
echo "    mount -o remount /home"
echo ""
echo "  Step 3: Create quota database files"
echo "    quotacheck -cugm /home"
echo "    -c = create new quota files"
echo "    -u = check user quotas"
echo "    -g = check group quotas"
echo "    -m = don't remount as read-only"
echo ""
echo "  Step 4: Enable quota enforcement"
echo "    quotaon /home"
echo ""
echo "  Step 5: Set quotas for a user"
echo "    edquota -u john"
echo "    Opens editor with:"
echo "      Filesystem  blocks  soft  hard  inodes  soft  hard"
echo "      /dev/sda1   5120    50000 60000  150    1000  1200"
echo ""
echo "  Step 6: Set grace period"
echo "    edquota -t"
echo "    Sets grace period for all users"

echo ""
echo "=== QUOTA COMMANDS ==="
echo ""
echo "  edquota -u john          Edit user quotas"
echo "  edquota -g developers   Edit group quotas"
echo "  edquota -t               Edit grace periods"
echo "  edquota -p john jane     Copy john's quotas to jane"
echo ""
echo "  repquota /home           Report all quotas on /home"
echo "  repquota -a              Report all filesystems"
echo "  repquota -ug /home       Users and groups"
echo ""
echo "  quota -u john            Show john's usage"
echo "  quota -g developers     Show group usage"
echo ""
echo "  quotaon /home            Enable enforcement"
echo "  quotaoff /home           Disable enforcement"
echo "  quotacheck -avugm        Rebuild all quota databases"

echo ""
echo "=== EXAM SCENARIOS ==="
echo ""
echo "  Q: User cannot create files but has disk space"
echo "  A: Inode hard quota reached (too many files)"
echo ""
echo "  Q: User gets warnings but can still write"
echo "  A: Exceeded soft limit, still in grace period"
echo ""
echo "  Q: User was writing fine, now suddenly blocked"
echo "  A: Grace period expired after exceeding soft limit"
echo ""
echo "  Q: How to give all new users the same quota?"
echo "  A: edquota -p template_user new_user"
echo ""
echo "  Q: What mount option enables user quotas?"
echo "  A: usrquota in /etc/fstab"

echo ""
echo "Bug fix #4 complete."
