#!/bin/bash
echo "================================================"
echo "  BUG FIX #10: Service Troubleshooting Decision Tree"
echo "  Root Cause: Domain 2 dropped to 67%"
echo "  Fix Target: Fast diagnosis of service failures"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== ROOT CAUSE ANALYSIS ==="
echo ""
echo "  Symptom: The exam gives a scenario where a service"
echo "  is misbehaving and asks what to check or what caused"
echo "  it. Need a systematic decision tree, not guessing."

echo ""
echo "=== DECISION TREE: SERVICE WON'T START ==="
echo ""
echo "  Step 1: What does systemd say?"
echo "    systemctl status service_name"
echo ""
echo "    Active: failed       -> check logs (Step 2)"
echo "    Active: inactive     -> was it enabled?"
echo "    Loaded: not-found    -> service doesn't exist"
echo "    Loaded: masked       -> service is masked"
echo ""
echo "  Step 2: What do the logs say?"
echo "    journalctl -u service_name -n 30"
echo ""
echo "    'Permission denied'    -> Step 3a"
echo "    'Address already in use' -> Step 3b"
echo "    'No such file'         -> Step 3c"
echo "    'Configuration error'  -> Step 3d"
echo "    SELinux denial          -> Step 3e"

echo ""
echo "  Step 3a: Permission denied"
echo "    ls -la /path/to/binary       Check binary permissions"
echo "    ls -la /path/to/config       Check config permissions"
echo "    ls -Z /path/to/files         Check SELinux context"
echo "    namei -l /full/path          Check each dir in path"
echo ""
echo "    Common fix: chown/chmod on files"
echo "    Common fix: restorecon for SELinux"
echo "    Common fix: User= directive in unit file"

echo ""
echo "  Step 3b: Address already in use (port conflict)"
echo "    ss -tlnp | grep PORT_NUMBER"
echo ""
echo "    Shows which process holds the port"
echo "    Fix: stop the other process, or change port"
echo "    Common: old instance still running"
echo "    Common: another service uses same port"

echo ""
echo "  Step 3c: No such file or directory"
echo "    ExecStart path wrong?      systemctl cat service"
echo "    Binary not installed?      which binary_name"
echo "    Config file missing?       ls -la config_path"
echo "    Working directory wrong?   check WorkingDirectory="
echo ""
echo "    Common: binary moved or not in PATH"
echo "    Common: config deleted or renamed"

echo ""
echo "  Step 3d: Configuration error"
echo "    Check syntax:"
echo "      nginx -t                 (nginx)"
echo "      apachectl configtest     (apache)"
echo "      named-checkconf          (BIND DNS)"
echo "      visudo -c                (sudoers)"
echo "      sshd -t                  (SSH)"
echo ""
echo "    Common: typo in config after recent edit"
echo "    Common: missing semicolon or bracket"

echo ""
echo "  Step 3e: SELinux blocking"
echo "    ausearch -m avc -ts recent"
echo "    sealert -a /var/log/audit/audit.log"
echo ""
echo "    Wrong file context -> restorecon"
echo "    Wrong port -> semanage port -a"
echo "    Missing boolean -> setsebool -P"

echo ""
echo "=== DECISION TREE: SERVICE STARTS BUT CRASHES ==="
echo ""
echo "  Keeps restarting (crash loop):"
echo "    systemctl status shows: activating (auto-restart)"
echo "    journalctl -u service -f       Watch live"
echo ""
echo "    Common causes:"
echo "    - Depends on service not yet ready (add After=)"
echo "    - Config valid syntax but wrong values (wrong DB host)"
echo "    - Out of memory (check dmesg for OOM killer)"
echo "    - File descriptor limit (check ulimit)"
echo ""
echo "    Check: RestartSec= in unit file"
echo "    If too low, service thrashes"
echo "    If too high, recovery is slow"

echo ""
echo "=== DECISION TREE: SERVICE RUNNING BUT NOT ACCESSIBLE ==="
echo ""
echo "  Service is active but users can't connect:"
echo ""
echo "  1. Is it listening?"
echo "     ss -tlnp | grep PORT"
echo "     If nothing: service not binding to correct interface"
echo "     Check: ListenAddress in config (0.0.0.0 vs 127.0.0.1)"
echo ""
echo "  2. Is the firewall blocking?"
echo "     firewall-cmd --list-all"
echo "     If port not listed: firewall-cmd --add-port=PORT/tcp"
echo ""
echo "  3. Is SELinux blocking?"
echo "     ausearch -m avc -ts recent"
echo ""
echo "  4. Is the client on the right network?"
echo "     ping server_ip from client"
echo "     traceroute to check path"

echo ""
echo "=== MASKED SERVICES ==="
echo ""
echo "  systemctl mask service        Prevent starting (even manually)"
echo "  systemctl unmask service      Allow starting again"
echo ""
echo "  Masking creates symlink to /dev/null"
echo "  Even 'systemctl start' won't work on masked service"
echo "  Used to prevent accidental start of dangerous services"
echo ""
echo "  Exam scenario: 'Service cannot be started by any means'"
echo "  Answer: service is masked"

echo ""
echo "=== ENABLE vs START vs MASK ==="
echo ""
echo "  State        Start Now?    Start on Boot?"
echo "  -----        ----------    --------------"
echo "  start        YES           no"
echo "  enable       no            YES"
echo "  enable --now YES           YES"
echo "  disable      (unchanged)   NO"
echo "  stop         NO            (unchanged)"
echo "  mask         BLOCKED       BLOCKED"
echo "  unmask       (unchanged)   (unchanged)"

echo ""
echo "=== EXAM QUICK REFERENCE ==="
echo ""
echo "  Scenario                          First Command"
echo "  --------                          -------------"
echo "  Service won't start               systemctl status + journalctl -u"
echo "  Service crashes repeatedly        journalctl -u -f (follow)"
echo "  Service runs but unreachable      ss -tlnp, firewall-cmd"
echo "  Service can't be started at all   check if masked"
echo "  Service starts before dependency  Add After= to unit file"
echo "  Service doesn't start on boot     systemctl enable"
echo "  Need to reload after config edit  systemctl reload (not restart)"
echo "  Changed unit file                 systemctl daemon-reload first"

echo ""
echo "Bug fix #10 complete."
