#!/bin/bash
echo "================================================"
echo "  Log Management Reference"
echo "  Linux+ XK0-006"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== SYSLOG / RSYSLOG ==="
echo ""
echo "  Traditional logging daemon"
echo "  Config: /etc/rsyslog.conf"
echo "  Additional: /etc/rsyslog.d/*.conf"
echo ""
echo "  Format: facility.priority    destination"
echo ""
echo "  Facilities (where the message comes from):"
echo "    auth       Authentication (login, sudo)"
echo "    authpriv   Private auth messages"
echo "    cron       Cron jobs"
echo "    daemon     System daemons"
echo "    kern       Kernel messages"
echo "    mail       Mail system"
echo "    user       User programs"
echo "    local0-7   Custom use"
echo ""
echo "  Priorities (severity levels):"
echo "    emerg   0   System unusable"
echo "    alert   1   Immediate action needed"
echo "    crit    2   Critical condition"
echo "    err     3   Error condition"
echo "    warning 4   Warning"
echo "    notice  5   Normal but significant"
echo "    info    6   Informational"
echo "    debug   7   Debug messages"
echo ""
echo "  Examples in rsyslog.conf:"
echo "    auth.*            /var/log/auth.log"
echo "    kern.*            /var/log/kern.log"
echo "    *.crit            /var/log/critical.log"
echo "    mail.err          /var/log/mail.err"
echo "    *.info;mail.none  /var/log/messages"
echo ""
echo "  The * means all. The .none means exclude."
echo "  Priority includes that level AND above."
echo "  auth.warning = warning + err + crit + alert + emerg"

echo ""
echo "=== JOURNALD (systemd journal) ==="
echo ""
echo "  Modern replacement for syslog"
echo "  Stores logs in binary format"
echo "  Config: /etc/systemd/journald.conf"
echo ""
echo "  journalctl commands:"
echo "    journalctl                    All logs"
echo "    journalctl -f                 Follow (live tail)"
echo "    journalctl -u nginx           Service-specific"
echo "    journalctl -p err             Priority err and above"
echo "    journalctl -p warning..err    Range of priorities"
echo "    journalctl --since today      Today only"
echo "    journalctl --since '1 hour ago'"
echo "    journalctl --since '2026-06-28 08:00'"
echo "    journalctl -b                 Current boot"
echo "    journalctl -b -1              Previous boot"
echo "    journalctl -b -2              Two boots ago"
echo "    journalctl _UID=1001         By user ID"
echo "    journalctl _PID=4521         By process ID"
echo "    journalctl -k                 Kernel messages only"
echo "    journalctl --disk-usage       Storage used by logs"
echo "    journalctl --vacuum-size=500M Trim to 500MB"
echo "    journalctl -o json            JSON output"
echo ""
echo "  Persistence:"
echo "    By default, journal may not survive reboot"
echo "    mkdir -p /var/log/journal"
echo "    systemctl restart systemd-journald"
echo "    Now logs persist across reboots"
echo ""
echo "  journald.conf settings:"
echo "    Storage=persistent     Save to disk"
echo "    SystemMaxUse=500M     Max disk usage"
echo "    MaxRetentionSec=1month Max retention"

echo ""
echo "=== LOG ROTATION ==="
echo ""
echo "  logrotate manages log file sizes"
echo "  Config: /etc/logrotate.conf"
echo "  Drop-ins: /etc/logrotate.d/"
echo ""
echo "  Example /etc/logrotate.d/nginx:"
echo "    /var/log/nginx/*.log {"
echo "        daily              Rotate daily"
echo "        rotate 14          Keep 14 old copies"
echo "        compress           Gzip old logs"
echo "        delaycompress      Don't compress most recent"
echo "        missingok          Don't error if log missing"
echo "        notifempty         Don't rotate empty files"
echo "        create 0640 nginx adm   Permissions for new file"
echo "        sharedscripts"
echo "        postrotate"
echo "            systemctl reload nginx"
echo "        endscript"
echo "    }"
echo ""
echo "  Rotation options:"
echo "    daily / weekly / monthly"
echo "    rotate N        Keep N old versions"
echo "    size 100M       Rotate when file exceeds size"
echo "    maxsize 500M    Force rotate at this size"
echo "    compress        Gzip rotated files"
echo "    dateext         Use date in rotated filename"
echo ""
echo "  Manual rotation:"
echo "    logrotate -f /etc/logrotate.conf"

echo ""
echo "=== LOGGER COMMAND ==="
echo ""
echo "  Write to syslog from command line or scripts:"
echo "    logger 'Backup completed successfully'"
echo "    logger -p auth.warning 'Suspicious login attempt'"
echo "    logger -t myapp 'Application started'"
echo ""
echo "  -p = facility.priority"
echo "  -t = tag (identifies the source)"

echo ""
echo "=== LOG FILE LOCATIONS (know these) ==="
echo ""
echo "  Debian/Ubuntu:              RHEL/CentOS:"
echo "  /var/log/syslog             /var/log/messages"
echo "  /var/log/auth.log           /var/log/secure"
echo "  /var/log/kern.log           /var/log/kern.log"
echo "  /var/log/dpkg.log           /var/log/dnf.log"
echo ""
echo "  Both:"
echo "  /var/log/boot.log           Boot messages"
echo "  /var/log/cron               Cron logs"
echo "  /var/log/dmesg              Hardware/driver messages"
echo "  /var/log/audit/audit.log    SELinux audit"
echo "  /var/log/wtmp               Login history (binary)"
echo "  /var/log/btmp               Failed logins (binary)"
echo "  /var/log/lastlog            Last login (binary)"
echo ""
echo "  Read binary logs:"
echo "    last                      Read wtmp"
echo "    lastb                     Read btmp"
echo "    lastlog                   Read lastlog"

echo ""
echo "Log management reference complete."
