#!/bin/bash
echo "================================================"
echo "  Networking for Linux+ Lab"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "--- 01: NETWORKING FUNDAMENTALS ---"
echo "Your network interfaces:"
ifconfig | grep -E "^[a-z]|inet "
echo ""
echo "OSI Layer 1-2 (Physical/Data Link):"
ifconfig en0 | grep ether
echo "  ^ That's your MAC address (Layer 2)"

echo ""
echo "--- 02: IP ADDRESSING & SUBNETTING ---"
echo "Your IP and subnet:"
ifconfig en0 | grep "inet "
echo ""
echo "Key subnets to know:"
echo "  /24 = 255.255.255.0 = 254 hosts"
echo "  /26 = 255.255.255.192 = 62 hosts"
echo "  /16 = 255.255.0.0 = 65,534 hosts"
echo "  /8  = 255.0.0.0 = 16 million hosts"
echo ""
echo "Private IP ranges (RFC 1918):"
echo "  10.0.0.0/8       (Class A)"
echo "  172.16.0.0/12    (Class B)"
echo "  192.168.0.0/16   (Class C)"

echo ""
echo "--- 03: TRANSPORT & PROTOCOLS ---"
echo "Common ports (exam tested):"
echo "  22  = SSH"
echo "  25  = SMTP"
echo "  53  = DNS"
echo "  80  = HTTP"
echo "  443 = HTTPS"
echo "  3306 = MySQL"
echo "  5432 = PostgreSQL"
echo ""
echo "TCP vs UDP:"
echo "  TCP = reliable, 3-way handshake (SYN, SYN-ACK, ACK)"
echo "  UDP = fast, no handshake (streaming, DNS queries)"
echo ""
echo "Open connections on this machine:"
netstat -an 2>/dev/null | grep ESTABLISHED | head -5 || echo "  Use: netstat -an | grep ESTABLISHED"

echo ""
echo "--- 04: DNS DEEP DIVE ---"
echo "Your DNS servers:"
cat /etc/resolv.conf 2>/dev/null | grep nameserver || scutil --dns | grep nameserver | head -3
echo ""
echo "DNS lookup examples:"
echo "  nslookup google.com:"
nslookup google.com 2>/dev/null | grep -A1 "Name:" || host google.com 2>/dev/null | head -1
echo ""
echo "Resolution order:"
echo "  1. /etc/hosts (local file)"
echo "  2. DNS servers (/etc/resolv.conf)"
echo "  Controlled by: /etc/nsswitch.conf"

echo ""
echo "--- 05: DHCP & NAT ---"
echo "Your default gateway:"
netstat -rn 2>/dev/null | grep default | head -1 || route -n get default 2>/dev/null | grep gateway
echo ""
echo "DHCP process (DORA):"
echo "  1. Discover - client broadcasts 'anyone have an IP?'"
echo "  2. Offer    - server says 'here, use this IP'"
echo "  3. Request  - client says 'I'll take that one'"
echo "  4. Acknowledge - server confirms the lease"
echo ""
echo "NAT: translates private IPs to public IPs"
echo "  Your private IP: $(ifconfig en0 | grep 'inet ' | awk '{print $2}')"
echo "  Your public IP:  (would need: curl ifconfig.me)"

echo ""
echo "--- 06: ROUTING ---"
echo "Routing table:"
netstat -rn 2>/dev/null | head -10 || route -n 2>/dev/null | head -10
echo ""
echo "Trace route to google.com (first 5 hops):"
echo "  traceroute -m 5 google.com (takes time, skip for now)"

echo ""
echo "--- 07: FIREWALLS ---"
echo "Linux firewall commands (exam tested):"
echo "  firewall-cmd --list-all           (firewalld - RHEL)"
echo "  ufw status                        (ufw - Ubuntu)"
echo "  iptables -L                       (iptables - legacy)"
echo ""
echo "  firewall-cmd --add-service=ssh    (allow SSH)"
echo "  firewall-cmd --add-port=8080/tcp  (allow port)"
echo "  ufw allow 22                      (allow SSH)"
echo "  ufw deny 3306                     (block MySQL)"

echo ""
echo "--- 08: TLS/SSL ---"
echo "Check a site's TLS certificate:"
echo "  openssl s_client -connect google.com:443 </dev/null 2>/dev/null | grep subject"
openssl s_client -connect google.com:443 </dev/null 2>/dev/null | grep "subject=" | head -1
echo ""
echo "TLS Handshake (exam tested):"
echo "  1. Client Hello    - 'I want to connect securely'"
echo "  2. Server Hello    - 'Here is my certificate'"
echo "  3. Key Exchange    - negotiate encryption keys"
echo "  4. Finished        - encrypted connection established"
echo ""
echo "Certificate files on Linux:"
echo "  /etc/ssl/certs/           - trusted CA certificates"
echo "  /etc/pki/tls/certs/       - RHEL certificate store"
echo "  /etc/ssl/private/          - private keys (600 perms)"

echo ""
echo "--- QUICK REFERENCE ---"
echo "Troubleshooting flow:"
echo "  1. ip addr / ifconfig    - Do I have an IP?"
echo "  2. ping gateway          - Can I reach the network?"
echo "  3. ping 8.8.8.8          - Can I reach the internet?"
echo "  4. ping google.com       - Does DNS work?"
echo "  5. ss -tlnp / netstat    - Is the service listening?"
echo "  6. firewall-cmd --list   - Is the firewall blocking?"

echo ""
echo "Networking lab complete."
