#!/bin/bash
echo "================================================"
echo "  Network Services Reference"
echo "  Linux+ XK0-006"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== NETWORK CONFIGURATION ==="
echo ""
echo "  Modern tools (ip command):"
echo "    ip addr show                  Show all interfaces"
echo "    ip addr add 10.0.0.5/24 dev eth0  Set IP"
echo "    ip addr del 10.0.0.5/24 dev eth0  Remove IP"
echo "    ip link set eth0 up           Bring interface up"
echo "    ip link set eth0 down         Bring interface down"
echo "    ip route show                 Show routing table"
echo "    ip route add default via 10.0.0.1  Set gateway"
echo "    ip neigh show                 ARP table (neighbors)"
echo ""
echo "  Legacy tools (still on exam):"
echo "    ifconfig eth0                 Show interface"
echo "    ifconfig eth0 10.0.0.5        Set IP (temporary)"
echo "    route -n                      Show routes"
echo "    route add default gw 10.0.0.1 Set gateway"
echo "    arp -a                        ARP table"
echo ""
echo "  Persistent config (Debian/Ubuntu - Netplan):"
echo "    /etc/netplan/*.yaml"
echo "    netplan apply                 Apply changes"
echo ""
echo "  Persistent config (RHEL - NetworkManager):"
echo "    nmcli con show                List connections"
echo "    nmcli con mod eth0 ipv4.addresses 10.0.0.5/24"
echo "    nmcli con mod eth0 ipv4.gateway 10.0.0.1"
echo "    nmcli con mod eth0 ipv4.method manual"
echo "    nmcli con up eth0             Apply"
echo "    /etc/NetworkManager/           Config directory"
echo ""
echo "  Persistent config (legacy):"
echo "    /etc/sysconfig/network-scripts/ifcfg-eth0  (RHEL)"
echo "    /etc/network/interfaces                     (Debian)"

echo ""
echo "=== DNS CLIENT CONFIGURATION ==="
echo ""
echo "  /etc/resolv.conf:"
echo "    nameserver 8.8.8.8"
echo "    nameserver 8.8.4.4"
echo "    search example.com"
echo ""
echo "  /etc/hosts (local overrides):"
echo "    127.0.0.1   localhost"
echo "    10.0.50.25  mes-prod.factory.local"
echo ""
echo "  /etc/nsswitch.conf (resolution order):"
echo "    hosts: files dns myhostname"
echo "    files = /etc/hosts first"
echo "    dns = resolv.conf servers second"
echo ""
echo "  Testing DNS:"
echo "    dig example.com                Full query"
echo "    dig @8.8.8.8 example.com       Query specific server"
echo "    dig example.com +short         Just the answer"
echo "    dig -x 8.8.8.8                 Reverse lookup"
echo "    nslookup example.com           Simple lookup"
echo "    host example.com               Quick lookup"
echo "    getent hosts example.com       Test full resolution"

echo ""
echo "=== DHCP ==="
echo ""
echo "  DORA process:"
echo "    Discover  Client broadcasts request"
echo "    Offer     Server offers IP and settings"
echo "    Request   Client accepts the offer"
echo "    Ack       Server confirms the lease"
echo ""
echo "  Client commands:"
echo "    dhclient eth0               Request new lease"
echo "    dhclient -r eth0            Release current lease"
echo ""
echo "  DHCP provides:"
echo "    IP address"
echo "    Subnet mask"
echo "    Default gateway"
echo "    DNS servers"
echo "    Lease duration"

echo ""
echo "=== NTP (Time Synchronization) ==="
echo ""
echo "  Why it matters:"
echo "    Log correlation across servers"
echo "    Certificate validation (time-sensitive)"
echo "    Kerberos authentication (5-min tolerance)"
echo "    Cron job accuracy"
echo ""
echo "  Modern: chronyd (RHEL default)"
echo "    Config: /etc/chrony.conf"
echo "    systemctl status chronyd"
echo "    chronyc sources                Show time sources"
echo "    chronyc tracking               Sync status"
echo ""
echo "  Legacy: ntpd"
echo "    Config: /etc/ntp.conf"
echo "    ntpq -p                        Show peers"
echo ""
echo "  timedatectl:"
echo "    timedatectl                    Show time info"
echo "    timedatectl set-ntp true       Enable NTP"
echo "    timedatectl set-timezone US/Central"
echo "    timedatectl list-timezones     All available zones"

echo ""
echo "=== HTTP SERVERS ==="
echo ""
echo "  Apache:"
echo "    Package: httpd (RHEL) / apache2 (Debian)"
echo "    Config: /etc/httpd/conf/httpd.conf (RHEL)"
echo "    Config: /etc/apache2/apache2.conf (Debian)"
echo "    Sites: /etc/apache2/sites-available/"
echo "    Enable: a2ensite sitename"
echo "    Disable: a2dissite sitename"
echo "    Modules: a2enmod rewrite"
echo "    Test: apachectl configtest"
echo "    Restart: systemctl restart httpd / apache2"
echo ""
echo "  Nginx:"
echo "    Package: nginx"
echo "    Config: /etc/nginx/nginx.conf"
echo "    Sites: /etc/nginx/conf.d/ or sites-available/"
echo "    Test: nginx -t"
echo "    Restart: systemctl restart nginx"
echo "    Reload: systemctl reload nginx (no downtime)"

echo ""
echo "=== SSH SERVER ==="
echo ""
echo "  Package: openssh-server"
echo "  Config: /etc/ssh/sshd_config"
echo "  Service: sshd"
echo ""
echo "  Key settings:"
echo "    Port 22"
echo "    PermitRootLogin no"
echo "    PasswordAuthentication no"
echo "    PubkeyAuthentication yes"
echo "    MaxAuthTries 3"
echo "    AllowUsers admin"

echo ""
echo "=== NETWORK DIAGNOSTIC TOOLS ==="
echo ""
echo "  Connectivity:"
echo "    ping host                    ICMP echo test"
echo "    ping -c 4 host              Send 4 packets"
echo "    ping6 host                   IPv6 ping"
echo ""
echo "  Path tracing:"
echo "    traceroute host              Show network hops"
echo "    tracepath host               No root needed"
echo "    mtr host                     Combined ping+traceroute"
echo ""
echo "  Port testing:"
echo "    ss -tlnp                     Listening ports"
echo "    nc -zv host port             Test specific port"
echo "    nmap host                    Port scan"
echo "    telnet host port             Test connectivity"
echo ""
echo "  Traffic capture:"
echo "    tcpdump -i eth0              Capture all traffic"
echo "    tcpdump -i eth0 port 80      HTTP traffic only"
echo "    tcpdump -w capture.pcap      Save to file"
echo ""
echo "  Bandwidth:"
echo "    iperf3 -s                    Start server"
echo "    iperf3 -c server_ip          Test bandwidth"

echo ""
echo "=== COMMON PORTS (must memorize) ==="
echo ""
echo "    20   FTP data"
echo "    21   FTP control"
echo "    22   SSH"
echo "    23   Telnet (insecure)"
echo "    25   SMTP (email send)"
echo "    53   DNS"
echo "    67   DHCP server"
echo "    68   DHCP client"
echo "    80   HTTP"
echo "    110  POP3 (email receive)"
echo "    123  NTP"
echo "    143  IMAP (email receive)"
echo "    443  HTTPS"
echo "    445  SMB (Windows sharing)"
echo "    514  Syslog"
echo "    636  LDAPS"
echo "    993  IMAPS"
echo "    995  POP3S"
echo "    3306 MySQL"
echo "    3389 RDP"
echo "    5432 PostgreSQL"
echo "    8080 HTTP alternate"

echo ""
echo "Network services reference complete."
