#!/bin/bash
echo "================================================"
echo "  SCENARIO 10: DNS Resolution Failure"
echo "  Enterprise Troubleshooting Simulation"
echo "  Date: $(date)"
echo "================================================"

cat << 'STORY'
SITUATION:
  Multiple users report they cannot access the MES web
  interface by name (http://mes-prod.factory.local).
  Pinging the IP address 10.0.50.25 works fine. Pinging
  the hostname fails. The application is running. This
  started after a network maintenance window last night.

OBJECTIVE:
  Diagnose the DNS resolution failure. Restore name
  resolution. Implement a fallback so this doesn't
  take down hostname-dependent services again.
STORY

echo ""
echo "--- STEP 1: Confirm the symptom ---"
echo '  $ ping -c 2 10.0.50.25'
cat << 'OUTPUT'
  PING 10.0.50.25: 64 bytes from 10.0.50.25: ttl=64 time=0.5ms
  2 packets transmitted, 2 received, 0% packet loss
OUTPUT
echo ""
echo '  $ ping -c 2 mes-prod.factory.local'
cat << 'OUTPUT'
  ping: mes-prod.factory.local: Temporary failure in name resolution
OUTPUT
echo ""
echo "  IP works. Hostname fails. This is a DNS problem."

echo ""
echo "--- STEP 2: Check DNS configuration ---"
echo '  $ cat /etc/resolv.conf'
cat << 'OUTPUT'
  # Generated by NetworkManager
  search factory.local
  nameserver 10.0.50.5
  nameserver 10.0.50.6
OUTPUT
echo ""
echo "  Two DNS servers configured. Let's test them."

echo ""
echo "--- STEP 3: Test DNS servers directly ---"
echo '  $ dig @10.0.50.5 mes-prod.factory.local'
cat << 'OUTPUT'
  ;; connection timed out; no servers could be reached
OUTPUT
echo ""
echo '  $ dig @10.0.50.6 mes-prod.factory.local'
cat << 'OUTPUT'
  ;; connection timed out; no servers could be reached
OUTPUT
echo ""
echo "  Both DNS servers unreachable. The network"
echo "  maintenance broke DNS server connectivity."

echo ""
echo "--- STEP 4: Verify DNS servers are down ---"
echo '  $ nc -zv 10.0.50.5 53 -w 3'
cat << 'OUTPUT'
  nc: connect to 10.0.50.5 port 53 (tcp) timed out
OUTPUT
echo ""
echo '  $ nc -zv 10.0.50.6 53 -w 3'
cat << 'OUTPUT'
  nc: connect to 10.0.50.6 port 53 (tcp) timed out
OUTPUT
echo ""
echo "  Port 53 (DNS) unreachable on both servers."
echo "  DNS service is down or network path is broken."

echo ""
echo "--- STEP 5: Test with public DNS as workaround ---"
echo '  $ dig @8.8.8.8 google.com +short'
cat << 'OUTPUT'
  142.250.80.46
OUTPUT
echo ""
echo "  Public DNS works. External resolution is fine."
echo "  Only internal DNS is broken."

echo ""
echo "--- STEP 6: Implement immediate workaround ---"
echo '  # Add critical hosts to /etc/hosts for immediate relief'
echo '  $ cat >> /etc/hosts << HOSTS'
cat << 'OUTPUT'
  # Emergency DNS workaround - INC-40835
  # Remove after internal DNS restored
  10.0.50.25    mes-prod.factory.local    mes-prod
  10.0.50.30    db-prod.factory.local     db-prod
  10.0.50.35    backup.factory.local      backup
OUTPUT
echo ""
echo '  $ ping -c 1 mes-prod.factory.local'
cat << 'OUTPUT'
  PING mes-prod.factory.local (10.0.50.25): 64 bytes ttl=64 time=0.5ms
OUTPUT
echo ""
echo "  Hostname resolves via /etc/hosts. Services restored."

echo ""
echo "--- STEP 7: Understand resolution order ---"
echo '  $ cat /etc/nsswitch.conf | grep hosts'
cat << 'OUTPUT'
  hosts:      files dns myhostname
OUTPUT
echo ""
cat << 'OUTPUT'
  Resolution order:
    1. files    = /etc/hosts (checked FIRST)
    2. dns      = /etc/resolv.conf DNS servers
    3. myhostname = local hostname fallback
  
  This is why /etc/hosts works as a workaround.
  The system checks it BEFORE trying DNS servers.
  
  nsswitch.conf controls the lookup order for:
    hosts     - hostname resolution
    passwd    - user accounts
    group     - group memberships
    shadow    - password hashes
OUTPUT

echo ""
echo "--- STEP 8: Add temporary public DNS fallback ---"
echo '  $ cat > /etc/resolv.conf << RESOLVCONF'
cat << 'OUTPUT'
  search factory.local
  nameserver 10.0.50.5
  nameserver 10.0.50.6
  nameserver 8.8.8.8
OUTPUT
echo ""
echo "  Added Google DNS as third fallback. If internal"
echo "  DNS fails, external names still resolve."
echo "  Internal names use /etc/hosts until DNS restored."

echo ""
echo "--- STEP 9: Notify network team ---"
echo '  $ logger "INC-40835: Internal DNS servers 10.0.50.5 and 10.0.50.6 unreachable. /etc/hosts workaround applied."'
echo ""
echo "  Network team informed. They investigate the DNS"
echo "  servers while production continues via /etc/hosts."

echo ""
echo "--- DNS TROUBLESHOOTING REFERENCE ---"
cat << 'SUMMARY'
  Key Files:
    /etc/resolv.conf       DNS server configuration
    /etc/hosts             Static hostname mappings
    /etc/nsswitch.conf     Name resolution order
    /etc/hostname          System hostname

  Diagnostic Commands:
    dig HOSTNAME                    Full DNS query
    dig @SERVER HOSTNAME            Query specific DNS server
    dig HOSTNAME +short             Just the IP answer
    nslookup HOSTNAME               Simple DNS lookup
    host HOSTNAME                   Quick DNS check
    getent hosts HOSTNAME           Test full resolution chain

  DNS Record Types (exam tested):
    A       Hostname to IPv4 address
    AAAA    Hostname to IPv6 address
    CNAME   Alias pointing to another name
    MX      Mail server for a domain
    NS      Nameserver for a domain
    PTR     Reverse lookup (IP to hostname)
    SOA     Start of authority (zone info)
    TXT     Text records (SPF, verification)
    SRV     Service location records

  Network Ports:
    53/tcp and 53/udp = DNS
    67/udp = DHCP server
    68/udp = DHCP client

  Common DNS Servers:
    8.8.8.8        Google Public DNS
    1.1.1.1        Cloudflare DNS
    9.9.9.9        Quad9 DNS

  Troubleshooting Flow:
    1. ping IP       (works? network is fine)
    2. ping hostname (fails? DNS problem)
    3. cat resolv.conf (correct servers?)
    4. dig @server   (server responding?)
    5. nc -zv IP 53  (port open?)
    6. /etc/hosts    (workaround while fixing)
SUMMARY

echo ""
echo "Scenario 10 complete."
