#!/bin/bash
echo "================================================"
echo "  Bash Scripting Reference"
echo "  Linux+ XK0-006 Domain 4: Scripting"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "--- SCRIPT BASICS ---"
echo ""
echo "  Shebang (first line of every script):"
echo "    #!/bin/bash       Use bash interpreter"
echo "    #!/bin/sh         Use sh (more portable)"
echo "    #!/usr/bin/env python3   Use python"
echo ""
echo "  Make executable: chmod 755 script.sh"
echo "  Run: ./script.sh"
echo ""
echo "  The shebang tells the OS which interpreter to use"
echo "  Without it, the script runs in the current shell"

echo ""
echo "--- VARIABLES ---"
echo ""
echo "  Assign (NO spaces around =):"
echo "    NAME='Marty'          String"
echo "    COUNT=10               Number"
echo "    TODAY=\$(date)          Command substitution"
echo "    FILES=\$(ls *.sh)      Capture command output"
echo ""
echo "  Use variables:"
echo "    echo \$NAME"
echo "    echo \${NAME}          Safer with curly braces"
echo "    echo \"Hello \$NAME\"    Inside double quotes"
echo "    echo 'Hello \$NAME'    Single quotes = literal (no expansion)"
echo ""
echo "  Special variables:"
echo "    \$0     Script name"
echo "    \$1-\$9  Arguments 1-9"
echo "    \$#     Number of arguments"
echo "    \$@     All arguments as separate words"
echo "    \$*     All arguments as one string"
echo "    \$?     Exit code of last command"
echo "    \$\$     Current process ID"
echo "    \$!     PID of last background process"

echo ""
echo "--- QUOTING ---"
echo ""
echo "  Double quotes \"...\" = variables expand"
echo "    echo \"Hello \$NAME\"  -> Hello Marty"
echo ""
echo "  Single quotes '...' = everything literal"
echo "    echo 'Hello \$NAME'  -> Hello \$NAME"
echo ""
echo "  Backticks \`...\` = command substitution (old style)"
echo "    echo \`date\`         Same as \$(date)"
echo "  Prefer \$() over backticks (nestable, readable)"

echo ""
echo "--- TEST CONDITIONS ---"
echo ""
echo "  Number comparisons:"
echo "    -eq    Equal"
echo "    -ne    Not equal"
echo "    -gt    Greater than"
echo "    -lt    Less than"
echo "    -ge    Greater or equal"
echo "    -le    Less or equal"
echo ""
echo "  String comparisons:"
echo "    =      Equal (in [ ])"
echo "    ==     Equal (in [[ ]])"
echo "    !=     Not equal"
echo "    -z     String is empty"
echo "    -n     String is not empty"
echo ""
echo "  File tests:"
echo "    -f     Is a regular file"
echo "    -d     Is a directory"
echo "    -e     Exists (file or directory)"
echo "    -r     Is readable"
echo "    -w     Is writable"
echo "    -x     Is executable"
echo "    -s     File is not empty (has size)"
echo "    -L     Is a symbolic link"
echo ""
echo "  Logic:"
echo "    &&     AND"
echo "    ||     OR"
echo "    !      NOT"

echo ""
echo "--- IF STATEMENTS ---"
echo ""
echo "  Basic:"
echo "    if [ \$COUNT -gt 10 ]; then"
echo "        echo 'More than 10'"
echo "    fi"
echo ""
echo "  If/else:"
echo "    if [ -f /etc/passwd ]; then"
echo "        echo 'File exists'"
echo "    else"
echo "        echo 'File missing'"
echo "    fi"
echo ""
echo "  If/elif/else:"
echo "    if [ \$SCORE -ge 90 ]; then"
echo "        echo 'A grade'"
echo "    elif [ \$SCORE -ge 80 ]; then"
echo "        echo 'B grade'"
echo "    else"
echo "        echo 'Below B'"
echo "    fi"
echo ""
echo "  CRITICAL: spaces inside [ ] are required"
echo "    [ \$x -gt 5 ]   CORRECT"
echo "    [\$x -gt 5]     WRONG (no spaces)"

echo ""
echo "--- LOOPS ---"
echo ""
echo "  For loop (list):"
echo "    for name in alice bob charlie; do"
echo "        echo \"Hello \$name\""
echo "    done"
echo ""
echo "  For loop (files):"
echo "    for file in *.sh; do"
echo "        echo \"Script: \$file\""
echo "    done"
echo ""
echo "  For loop (C-style):"
echo "    for ((i=1; i<=5; i++)); do"
echo "        echo \"Count: \$i\""
echo "    done"
echo ""
echo "  While loop:"
echo "    COUNT=0"
echo "    while [ \$COUNT -lt 5 ]; do"
echo "        echo \$COUNT"
echo "        COUNT=\$((COUNT + 1))"
echo "    done"
echo ""
echo "  While read (process file line by line):"
echo "    while read -r line; do"
echo "        echo \"\$line\""
echo "    done < /etc/passwd"
echo ""
echo "  Until loop (runs until condition is TRUE):"
echo "    until [ \$COUNT -ge 5 ]; do"
echo "        echo \$COUNT"
echo "        COUNT=\$((COUNT + 1))"
echo "    done"

echo ""
echo "--- CASE STATEMENT ---"
echo ""
echo "    case \$input in"
echo "        start) echo 'Starting' ;;"
echo "        stop)  echo 'Stopping' ;;"
echo "        *)     echo 'Unknown'  ;;"
echo "    esac"
echo ""
echo "  case = if/elif chain for pattern matching"
echo "  ;; ends each option"
echo "  *) is the default/catch-all"
echo "  esac closes case (case backwards)"

echo ""
echo "--- FUNCTIONS ---"
echo ""
echo "  Define:"
echo "    greet() {"
echo "        echo \"Hello \$1\""
echo "    }"
echo ""
echo "  Call:"
echo "    greet Marty"
echo ""
echo "  Return values:"
echo "    Functions use exit codes (0-255)"
echo "    return 0    = success"
echo "    return 1    = failure"
echo "    Check with \$? after calling"
echo ""
echo "  Capture output:"
echo "    result=\$(greet Marty)"

echo ""
echo "--- INPUT/OUTPUT ---"
echo ""
echo "  Read user input:"
echo "    read -p 'Enter name: ' NAME"
echo "    read -s -p 'Password: ' PASS    -s = silent (passwords)"
echo "    read -t 10 -p 'Quick: ' ANS     -t = timeout in seconds"
echo ""
echo "  Redirection:"
echo "    command > file     Overwrite file with stdout"
echo "    command >> file    Append stdout to file"
echo "    command 2> file    Redirect stderr to file"
echo "    command &> file    Redirect both stdout and stderr"
echo "    command 2>&1       Redirect stderr to stdout"
echo "    command < file     Read stdin from file"
echo "    command << EOF     Here document (inline input)"

echo ""
echo "--- ERROR HANDLING ---"
echo ""
echo "  Exit codes:"
echo "    exit 0     Success"
echo "    exit 1     General error"
echo "    \$?         Check last exit code"
echo ""
echo "  set options (put at top of script):"
echo "    set -e     Exit on any error"
echo "    set -u     Error on undefined variables"
echo "    set -o pipefail   Catch errors in pipes"
echo "    set -x     Debug mode (print each command)"
echo ""
echo "  Common pattern:"
echo "    #!/bin/bash"
echo "    set -euo pipefail"

echo ""
echo "--- ARITHMETIC ---"
echo ""
echo "    result=\$((5 + 3))       Addition"
echo "    result=\$((10 - 4))      Subtraction"
echo "    result=\$((3 * 7))       Multiplication"
echo "    result=\$((20 / 4))      Division (integer only)"
echo "    result=\$((17 % 5))      Modulo (remainder)"
echo "    ((count++))              Increment"
echo "    ((count--))              Decrement"

echo ""
echo "Bash scripting reference complete."
