#!/bin/bash
echo "================================================"
echo "  Security Deep Dive"
echo "  Linux+ XK0-006 Domain 3: Security"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== FIREWALL DEEP DIVE ==="
echo ""
echo "  --- firewalld (RHEL/CentOS) ---"
echo "  Service: systemctl start/enable firewalld"
echo ""
echo "  Zones (exam tested):"
echo "    drop        Drop all incoming, no reply"
echo "    block       Reject incoming with message"
echo "    public      Default zone, limited trust"
echo "    external    NAT masquerading"
echo "    internal    Trusted internal network"
echo "    dmz         Demilitarized zone"
echo "    trusted     Accept all connections"
echo ""
echo "  Commands:"
echo "    firewall-cmd --get-default-zone"
echo "    firewall-cmd --set-default-zone=public"
echo "    firewall-cmd --list-all"
echo "    firewall-cmd --add-service=http --permanent"
echo "    firewall-cmd --add-port=8080/tcp --permanent"
echo "    firewall-cmd --remove-service=http --permanent"
echo "    firewall-cmd --reload"
echo ""
echo "  CRITICAL: --permanent makes it survive reboot"
echo "  Without --permanent, rule is lost on restart"
echo "  Always --reload after --permanent changes"
echo ""
echo "  --- ufw (Ubuntu) ---"
echo "    ufw enable                 Turn on firewall"
echo "    ufw disable                Turn off"
echo "    ufw status verbose         Show rules"
echo "    ufw allow 22               Allow SSH"
echo "    ufw deny 3306              Block MySQL"
echo "    ufw allow from 10.0.0.0/24 Allow subnet"
echo "    ufw delete allow 22        Remove rule"
echo ""
echo "  --- iptables (legacy but exam tested) ---"
echo "    Chains: INPUT, OUTPUT, FORWARD"
echo "    Targets: ACCEPT, DROP, REJECT, LOG"
echo ""
echo "    iptables -L -n             List all rules"
echo "    iptables -A INPUT -p tcp --dport 22 -j ACCEPT"
echo "    iptables -A INPUT -p tcp --dport 80 -j ACCEPT"
echo "    iptables -A INPUT -j DROP  Drop everything else"
echo "    iptables -F                Flush all rules"
echo ""
echo "    -A = Append rule"
echo "    -I = Insert at top (higher priority)"
echo "    -D = Delete rule"
echo "    -p = Protocol (tcp, udp, icmp)"
echo "    --dport = Destination port"
echo "    -s = Source IP"
echo "    -j = Jump to target (ACCEPT/DROP)"
echo ""
echo "  Save iptables:"
echo "    iptables-save > /etc/iptables/rules.v4"
echo "    iptables-restore < /etc/iptables/rules.v4"

echo ""
echo "=== SELinux DEEP DIVE ==="
echo ""
echo "  Modes:"
echo "    Enforcing    Blocks AND logs violations"
echo "    Permissive   Logs but does NOT block"
echo "    Disabled     Completely off"
echo ""
echo "  Check/set mode:"
echo "    getenforce                    Current mode"
echo "    setenforce 1                  Set enforcing (temp)"
echo "    setenforce 0                  Set permissive (temp)"
echo "    /etc/selinux/config           Permanent setting"
echo "    SELINUX=enforcing             In the config file"
echo ""
echo "  Context labels (user:role:type:level):"
echo "    ls -Z file                    Show file context"
echo "    ps -Z                         Show process context"
echo ""
echo "  Fix contexts:"
echo "    restorecon -Rv /path          Restore to defaults"
echo "    semanage fcontext -a -t httpd_sys_content_t '/web(/.*)?'"
echo "    restorecon -Rv /web           Apply the rule"
echo ""
echo "  Troubleshoot:"
echo "    ausearch -m avc -ts recent    Find denials"
echo "    sealert -a /var/log/audit/audit.log   Readable alerts"
echo "    audit2why                     Explain why denied"
echo ""
echo "  Booleans:"
echo "    getsebool -a | grep httpd     List httpd booleans"
echo "    setsebool -P httpd_can_network_connect on"
echo "    -P = Permanent (survives reboot)"
echo ""
echo "  NEVER disable SELinux to fix a problem."
echo "  Always fix the context or boolean."

echo ""
echo "=== AppArmor (Ubuntu/SUSE) ==="
echo ""
echo "  Alternative to SELinux"
echo "  Uses profiles instead of labels"
echo ""
echo "  Commands:"
echo "    aa-status                     Show profile status"
echo "    aa-enforce /path/to/profile   Set to enforce"
echo "    aa-complain /path/to/profile  Set to complain (log only)"
echo "    aa-disable /path/to/profile   Disable profile"
echo ""
echo "  Profiles location: /etc/apparmor.d/"
echo "  Logs: /var/log/syslog or journalctl"

echo ""
echo "=== CRYPTOGRAPHY ==="
echo ""
echo "  Symmetric encryption (same key both sides):"
echo "    AES, DES, 3DES, Blowfish"
echo "    Faster, used for bulk data"
echo ""
echo "  Asymmetric encryption (public + private key pair):"
echo "    RSA, ECDSA, Ed25519"
echo "    Slower, used for key exchange and authentication"
echo ""
echo "  Hashing (one-way, cannot reverse):"
echo "    MD5 (insecure), SHA-256, SHA-512"
echo "    Used for password storage and file verification"
echo ""
echo "  File hashing commands:"
echo "    md5sum file              MD5 hash"
echo "    sha256sum file           SHA-256 hash"
echo "    sha512sum file           SHA-512 hash"
echo ""
echo "  GPG (file encryption):"
echo "    gpg -c file              Encrypt with passphrase"
echo "    gpg file.gpg             Decrypt"
echo "    gpg --gen-key            Generate key pair"
echo ""
echo "  LUKS (disk encryption):"
echo "    cryptsetup luksFormat /dev/sda3"
echo "    cryptsetup luksOpen /dev/sda3 secure"
echo "    mkfs.ext4 /dev/mapper/secure"
echo "    mount /dev/mapper/secure /mnt"
echo "    cryptsetup luksClose secure"

echo ""
echo "=== CERTIFICATE MANAGEMENT ==="
echo ""
echo "  TLS/SSL certificates:"
echo "    Generate private key:"
echo "      openssl genrsa -out server.key 4096"
echo ""
echo "    Generate CSR (Certificate Signing Request):"
echo "      openssl req -new -key server.key -out server.csr"
echo ""
echo "    Self-signed certificate:"
echo "      openssl req -x509 -nodes -days 365 \\"
echo "        -newkey rsa:4096 -keyout server.key -out server.crt"
echo ""
echo "  Certificate locations:"
echo "    /etc/ssl/certs/              Trusted CA certs (Debian)"
echo "    /etc/pki/tls/certs/          Trusted CA certs (RHEL)"
echo "    /etc/ssl/private/            Private keys (600 perms)"
echo ""
echo "  Verify certificate:"
echo "    openssl x509 -in cert.crt -text -noout"
echo "    openssl s_client -connect host:443"

echo ""
echo "=== SECURITY SCANNING ==="
echo ""
echo "  Open ports:"
echo "    ss -tlnp                     Listening ports"
echo "    nmap -sV host                Port scan with services"
echo "    nmap -sS host                SYN scan (stealth)"
echo ""
echo "  File integrity:"
echo "    aide --init                   Initialize baseline"
echo "    aide --check                  Check for changes"
echo "    /etc/aide/aide.conf           AIDE configuration"
echo ""
echo "  Find security issues:"
echo "    find / -perm -4000            Find SUID files"
echo "    find / -perm -2000            Find SGID files"
echo "    find / -nouser                Files with no owner"
echo "    find / -nogroup               Files with no group"
echo "    last                          Recent logins"
echo "    lastb                         Failed login attempts"
echo "    who                           Currently logged in"
echo "    w                             Who and what they're doing"

echo ""
echo "=== SECURITY BEST PRACTICES ==="
echo ""
echo "  1. Principle of least privilege"
echo "  2. Keep systems patched and updated"
echo "  3. Use SSH keys, disable password auth"
echo "  4. Enable and configure firewall"
echo "  5. Keep SELinux/AppArmor enforcing"
echo "  6. Monitor logs regularly"
echo "  7. Use strong password policies (PAM)"
echo "  8. Encrypt sensitive data at rest and in transit"
echo "  9. Regular security audits (find SUID, check perms)"
echo "  10. Document everything"

echo ""
echo "Security deep dive complete."
