#!/bin/bash
echo "================================================"
echo "  SSH Security Reference"
echo "  Linux+ XK0-006 Domain 3: Security"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "--- SSH KEY TYPES ---"
echo ""
echo "  Generate keys:"
echo "    ssh-keygen -t ed25519 -C 'work laptop'    Modern (recommended)"
echo "    ssh-keygen -t rsa -b 4096                  RSA (compatible)"
echo "    ssh-keygen -t ecdsa -b 521                 Elliptic curve"
echo ""
echo "  Key files created:"
echo "    ~/.ssh/id_ed25519        Private key (NEVER share)"
echo "    ~/.ssh/id_ed25519.pub    Public key (share freely)"

echo ""
echo "--- SSH FILE PERMISSIONS (exam tested) ---"
echo ""
echo "  These MUST be exact or SSH silently refuses:"
echo "    ~/.ssh/                  700  drwx------"
echo "    ~/.ssh/id_ed25519        600  -rw-------"
echo "    ~/.ssh/id_ed25519.pub    644  -rw-r--r--"
echo "    ~/.ssh/authorized_keys   600  -rw-------"
echo "    ~/.ssh/config            600  -rw-------"
echo "    ~/.ssh/known_hosts       644  -rw-r--r--"
echo ""
echo "  Common mistake: permissions too open = SSH rejects key"
echo "  Fix: chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_*"

echo ""
echo "--- SSH CONFIG FILE (~/.ssh/config) ---"
echo ""
echo "  Saves typing long SSH commands:"
echo ""
echo "  Host factory-jump"
echo "      HostName jump.factory.com"
echo "      User admin"
echo "      Port 2222"
echo "      IdentityFile ~/.ssh/factory_key"
echo ""
echo "  Host factory-db"
echo "      HostName 10.0.50.30"
echo "      User dbadmin"
echo "      ProxyJump factory-jump"
echo ""
echo "  Usage: ssh factory-db"
echo "  (One command, auto-jumps through bastion)"

echo ""
echo "--- SSHD SERVER HARDENING (/etc/ssh/sshd_config) ---"
echo ""
echo "  Security settings (exam tested):"
echo ""
echo "  PermitRootLogin no              Disable root SSH login"
echo "  PasswordAuthentication no       Keys only, no passwords"
echo "  PubkeyAuthentication yes        Enable key authentication"
echo "  MaxAuthTries 3                  Limit failed attempts"
echo "  MaxSessions 5                   Limit concurrent sessions"
echo "  AllowUsers admin deploy         Whitelist specific users"
echo "  AllowGroups sshusers            Whitelist by group"
echo "  DenyUsers guest                 Block specific users"
echo "  Port 2222                       Non-standard port"
echo "  LoginGraceTime 60               Seconds to authenticate"
echo "  ClientAliveInterval 300         Timeout idle sessions"
echo "  ClientAliveCountMax 2           Disconnect after 2 missed"
echo "  X11Forwarding no               Disable GUI forwarding"
echo "  Protocol 2                      SSH version 2 only"
echo ""
echo "  After changes:"
echo "    systemctl restart sshd"

echo ""
echo "--- SSH TUNNELING ---"
echo ""
echo "  Local tunnel (access remote service locally):"
echo "    ssh -L 5432:db-server:5432 jump-server"
echo "    Then: psql -h localhost -p 5432"
echo ""
echo "  Remote tunnel (expose local to remote):"
echo "    ssh -R 8080:localhost:3000 remote-server"
echo "    Remote users access your app on port 8080"
echo ""
echo "  Dynamic tunnel (SOCKS proxy):"
echo "    ssh -D 1080 jump-server"
echo "    Configure browser to use SOCKS localhost:1080"
echo ""
echo "  Flags:"
echo "    -L  Local forward"
echo "    -R  Remote forward"
echo "    -D  Dynamic (SOCKS proxy)"
echo "    -N  No remote command (tunnel only)"
echo "    -f  Background (fork)"

echo ""
echo "--- SCP AND SFTP ---"
echo ""
echo "  Copy files over SSH:"
echo "    scp file.txt user@server:/path/        Upload"
echo "    scp user@server:/path/file.txt .       Download"
echo "    scp -r folder/ user@server:/path/      Upload directory"
echo "    scp -P 2222 file.txt user@server:/     Custom port"
echo ""
echo "  SFTP interactive:"
echo "    sftp user@server"
echo "    sftp> put localfile.txt"
echo "    sftp> get remotefile.txt"
echo "    sftp> ls"
echo "    sftp> exit"

echo ""
echo "--- KNOWN HOSTS ---"
echo ""
echo "  ~/.ssh/known_hosts stores server fingerprints"
echo "  First connection: 'Are you sure?' -> type yes"
echo "  If fingerprint changes: WARNING: REMOTE HOST ID CHANGED"
echo ""
echo "  Fix (after verifying server is legit):"
echo "    ssh-keygen -R hostname"
echo "  This removes the old fingerprint"

echo ""
echo "--- SSH AGENT ---"
echo ""
echo "  Avoid typing passphrase every time:"
echo "    eval \$(ssh-agent)"
echo "    ssh-add ~/.ssh/id_ed25519"
echo "    ssh-add -l                    List loaded keys"
echo "    ssh-add -D                    Remove all keys"

echo ""
echo "SSH security reference complete."
