#!/bin/bash
echo "================================================"
echo "  Storage Management Reference"
echo "  Linux+ XK0-006 Study Guide"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "--- DISK PARTITIONING ---"
echo ""
echo "  Partition Tools:"
echo "    fdisk /dev/sda         MBR partitioning (interactive)"
echo "    gdisk /dev/sda         GPT partitioning (interactive)"
echo "    parted /dev/sda        Both MBR and GPT"
echo ""
echo "  MBR vs GPT:"
echo "    MBR: max 4 primary partitions, 2TB max disk size"
echo "    GPT: 128 partitions, 9.4ZB max disk size"
echo "    Modern systems use GPT with UEFI boot"
echo ""
echo "  View partitions:"
echo "    lsblk                  Tree view of block devices"
echo "    fdisk -l               List all partitions"
echo "    blkid                  Show UUIDs and filesystem types"
echo "    cat /proc/partitions   Kernel view of partitions"

echo ""
echo "--- FILESYSTEM CREATION ---"
echo ""
echo "  Create filesystems:"
echo "    mkfs.ext4 /dev/sda1    Create ext4 filesystem"
echo "    mkfs.xfs /dev/sda1     Create XFS filesystem"
echo "    mkfs.btrfs /dev/sda1   Create Btrfs filesystem"
echo "    mkswap /dev/sda2       Create swap space"
echo ""
echo "  Filesystem types (exam tested):"
echo "    ext4    - Default Linux, supports shrink and grow"
echo "    xfs     - RHEL default, grow only (NO shrink)"
echo "    btrfs   - Copy-on-write, snapshots, SUSE default"
echo "    vfat    - FAT32, USB drives, EFI boot partition"
echo "    swap    - Virtual memory space"

echo ""
echo "--- MOUNTING ---"
echo ""
echo "  Mount commands:"
echo "    mount /dev/sda1 /mnt          Mount a partition"
echo "    mount -t ext4 /dev/sda1 /mnt  Specify filesystem type"
echo "    mount -o ro /dev/sda1 /mnt    Mount read-only"
echo "    umount /mnt                   Unmount"
echo "    umount -l /mnt                Lazy unmount (force)"
echo ""
echo "  View mounts:"
echo "    mount                   List all mounted filesystems"
echo "    df -h                   Disk usage by filesystem"
echo "    df -i                   Inode usage"
echo "    findmnt                 Tree view of mounts"
echo ""
echo "  Persistent mounts (/etc/fstab):"
echo "    UUID=xxxx  /data  ext4  defaults  0  2"
echo ""
echo "  fstab columns:"
echo "    1. Device (UUID or /dev/xxx)"
echo "    2. Mount point"
echo "    3. Filesystem type"
echo "    4. Options (defaults, ro, noexec, nosuid)"
echo "    5. Dump (0=skip, 1=backup)"
echo "    6. Pass (0=skip, 1=root check, 2=other check)"
echo ""
echo "  Mount options (exam tested):"
echo "    defaults   = rw, suid, dev, exec, auto, nouser, async"
echo "    ro         = read-only"
echo "    noexec     = cannot execute binaries"
echo "    nosuid     = ignore SUID bits"
echo "    nodev      = ignore device files"
echo "    noatime    = dont update access time (performance)"

echo ""
echo "--- SWAP MANAGEMENT ---"
echo ""
echo "  Create and enable swap:"
echo "    mkswap /dev/sda2       Format as swap"
echo "    swapon /dev/sda2       Enable swap partition"
echo "    swapoff /dev/sda2      Disable swap"
echo "    swapon --show          Show active swap"
echo "    free -h                See swap usage"
echo ""
echo "  Swap file (alternative to partition):"
echo "    dd if=/dev/zero of=/swapfile bs=1M count=4096"
echo "    chmod 600 /swapfile"
echo "    mkswap /swapfile"
echo "    swapon /swapfile"
echo "    Add to /etc/fstab: /swapfile swap swap defaults 0 0"

echo ""
echo "--- FILESYSTEM MAINTENANCE ---"
echo ""
echo "  Check and repair:"
echo "    fsck /dev/sda1           Check filesystem (UNMOUNT FIRST)"
echo "    fsck -y /dev/sda1        Auto-fix errors"
echo "    e2fsck /dev/sda1         ext4 specific check"
echo "    xfs_repair /dev/sda1     XFS specific repair"
echo ""
echo "  CRITICAL: Never run fsck on a mounted filesystem!"
echo ""
echo "  Resize filesystems:"
echo "    resize2fs /dev/vg/lv     Resize ext4 (online OK)"
echo "    xfs_growfs /mountpoint   Grow XFS (online, NO shrink)"

echo ""
echo "--- DISK USAGE ---"
echo ""
echo "  Space analysis:"
echo "    df -h             Filesystem usage"
echo "    du -sh /var       Directory size"
echo "    du -sh /* | sort -rh | head -10   Biggest directories"
echo "    ncdu              Interactive disk usage (install)"

echo ""
echo "--- LVM QUICK REFERENCE ---"
echo ""
echo "  Flow: Disk -> PV -> VG -> LV -> Filesystem"
echo ""
echo "  Physical Volumes:"
echo "    pvcreate /dev/sdb"
echo "    pvs"
echo ""
echo "  Volume Groups:"
echo "    vgcreate vg_data /dev/sdb"
echo "    vgextend vg_data /dev/sdc"
echo "    vgs"
echo ""
echo "  Logical Volumes:"
echo "    lvcreate -L 50G -n lv_data vg_data"
echo "    lvextend -L +20G /dev/vg_data/lv_data"
echo "    lvs"
echo ""
echo "  Then: mkfs.ext4 /dev/vg_data/lv_data"
echo "  Then: mount /dev/vg_data/lv_data /data"

echo ""
echo "Storage management reference complete."
