#!/bin/bash
echo "================================================"
echo "  System Management Deep Dive"
echo "  Linux+ XK0-006 Domain 1: System Management"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== BOOT PROCESS (exam loves this) ==="
echo ""
echo "  1. BIOS/UEFI"
echo "     - POST (Power-On Self Test)"
echo "     - Finds boot device (disk, USB, network)"
echo "     - BIOS uses MBR | UEFI uses ESP (EFI System Partition)"
echo ""
echo "  2. Bootloader (GRUB2)"
echo "     - Loads kernel and initramfs into memory"
echo "     - Config: /boot/grub2/grub.cfg"
echo "     - DO NOT edit grub.cfg directly"
echo "     - Edit /etc/default/grub then run grub2-mkconfig"
echo ""
echo "  3. Kernel"
echo "     - Loads into memory"
echo "     - Initializes hardware"
echo "     - Mounts initramfs as temporary root"
echo ""
echo "  4. initramfs"
echo "     - Temporary filesystem with drivers"
echo "     - Loads storage drivers to access real root"
echo "     - Hands off to real root filesystem"
echo ""
echo "  5. systemd (PID 1)"
echo "     - First process started by kernel"
echo "     - Manages all other services"
echo "     - Reads target to determine boot level"

echo ""
echo "=== GRUB2 CONFIGURATION ==="
echo ""
echo "  Files:"
echo "    /etc/default/grub              Edit this file"
echo "    /boot/grub2/grub.cfg           Generated (don't edit)"
echo "    /etc/grub.d/                   Menu entry scripts"
echo ""
echo "  Common settings in /etc/default/grub:"
echo "    GRUB_TIMEOUT=5                 Seconds to show menu"
echo "    GRUB_DEFAULT=0                 Boot first entry"
echo "    GRUB_CMDLINE_LINUX=\"quiet\"     Kernel parameters"
echo ""
echo "  After changes:"
echo "    grub2-mkconfig -o /boot/grub2/grub.cfg    (RHEL)"
echo "    update-grub                                (Ubuntu)"
echo ""
echo "  Kernel parameters (exam tested):"
echo "    quiet              Suppress boot messages"
echo "    single / 1         Boot to single user mode"
echo "    init=/bin/bash     Boot directly to shell (recovery)"
echo "    rd.break           Break into initramfs (password reset)"

echo ""
echo "=== KERNEL MANAGEMENT ==="
echo ""
echo "  View kernel info:"
echo "    uname -r            Kernel version"
echo "    uname -a            All system info"
echo "    uname -m            Architecture (x86_64, arm64)"
echo ""
echo "  Kernel modules:"
echo "    lsmod                     List loaded modules"
echo "    modprobe module_name      Load a module"
echo "    modprobe -r module_name   Unload a module"
echo "    modinfo module_name       Module details"
echo "    /etc/modprobe.d/          Persistent module config"
echo "    /etc/modules-load.d/      Auto-load at boot"
echo ""
echo "  Kernel parameters (runtime):"
echo "    sysctl -a                    List all parameters"
echo "    sysctl net.ipv4.ip_forward   Check specific param"
echo "    sysctl -w net.ipv4.ip_forward=1   Set temporarily"
echo "    /etc/sysctl.conf             Persistent settings"
echo "    sysctl -p                    Reload sysctl.conf"

echo ""
echo "=== PROCESS MANAGEMENT ==="
echo ""
echo "  View processes:"
echo "    ps aux                    All processes with details"
echo "    ps -ef                    Full format listing"
echo "    pstree                    Tree view of processes"
echo "    top / htop                Real-time monitoring"
echo "    pgrep -a nginx            Find process by name"
echo ""
echo "  Process states:"
echo "    R  Running"
echo "    S  Sleeping (waiting for event)"
echo "    D  Uninterruptible sleep (waiting for I/O)"
echo "    T  Stopped (suspended)"
echo "    Z  Zombie (finished but parent hasn't collected)"
echo ""
echo "  Signals:"
echo "    kill PID                  Send SIGTERM (15) - graceful"
echo "    kill -9 PID              Send SIGKILL (9) - force"
echo "    kill -1 PID              Send SIGHUP (1) - reload"
echo "    kill -STOP PID           Suspend process"
echo "    kill -CONT PID           Resume process"
echo "    killall nginx            Kill all by name"
echo "    pkill -u testuser        Kill all by user"
echo ""
echo "  Background/Foreground:"
echo "    command &                Run in background"
echo "    jobs                     List background jobs"
echo "    fg %1                    Bring job 1 to foreground"
echo "    bg %1                    Resume job 1 in background"
echo "    nohup command &          Survives terminal close"
echo "    screen / tmux            Terminal multiplexers"

echo ""
echo "=== FILESYSTEM HIERARCHY (FHS) ==="
echo ""
echo "  /           Root of everything"
echo "  /bin        Essential user commands (ls, cp, mv)"
echo "  /sbin       Essential system commands (fdisk, reboot)"
echo "  /etc        Configuration files"
echo "  /home       User home directories"
echo "  /root       Root user home directory"
echo "  /var        Variable data (logs, mail, spool)"
echo "  /var/log    Log files"
echo "  /var/tmp    Persistent temp files (survive reboot)"
echo "  /tmp        Temporary files (cleared on reboot)"
echo "  /usr        User programs and data"
echo "  /usr/bin    User binaries"
echo "  /usr/sbin   System binaries"
echo "  /usr/local  Manually installed software"
echo "  /opt        Optional/third-party software"
echo "  /dev        Device files"
echo "  /proc       Virtual filesystem (kernel info)"
echo "  /sys        Virtual filesystem (hardware info)"
echo "  /boot       Bootloader and kernel images"
echo "  /lib        Shared libraries"
echo "  /mnt        Temporary mount point"
echo "  /media      Removable media mount point"
echo "  /srv        Service data (web, FTP)"

echo ""
echo "=== LOCALIZATION AND TIME ==="
echo ""
echo "  Time:"
echo "    date                       Current date/time"
echo "    timedatectl                Time and timezone info"
echo "    timedatectl set-timezone America/Chicago"
echo "    timedatectl set-ntp true   Enable NTP sync"
echo "    /etc/chrony.conf           NTP config (RHEL)"
echo "    /etc/ntp.conf              NTP config (legacy)"
echo "    hwclock                    Hardware clock"
echo "    hwclock --systohc          Sync HW clock to system"
echo ""
echo "  Locale:"
echo "    locale                     Current locale settings"
echo "    localectl                  System locale"
echo "    localectl set-locale LANG=en_US.UTF-8"
echo "    /etc/locale.conf           Persistent locale"
echo ""
echo "  Keyboard:"
echo "    localectl set-keymap us    Set keyboard layout"
echo "    loadkeys us                Temporary keymap change"

echo ""
echo "=== SOFTWARE MANAGEMENT ==="
echo ""
echo "  Compile from source:"
echo "    tar xzf source.tar.gz"
echo "    cd source/"
echo "    ./configure"
echo "    make"
echo "    make install"
echo ""
echo "  Libraries:"
echo "    ldd /usr/bin/program       Show shared libraries"
echo "    ldconfig                   Update library cache"
echo "    /etc/ld.so.conf.d/         Library path config"
echo "    LD_LIBRARY_PATH            Environment override"

echo ""
echo "=== VIRTUALIZATION BASICS ==="
echo ""
echo "  Types:"
echo "    Type 1 (bare metal): VMware ESXi, KVM, Hyper-V"
echo "    Type 2 (hosted): VirtualBox, VMware Workstation"
echo ""
echo "  Container vs VM:"
echo "    VM:        Full OS, own kernel, heavy, isolated"
echo "    Container: Shares host kernel, lightweight, fast"
echo ""
echo "  Container commands:"
echo "    docker ps                  List running containers"
echo "    docker images              List images"
echo "    docker run -d image        Run container"
echo "    docker exec -it name sh    Shell into container"
echo "    docker logs name           View container logs"
echo "    podman                     Docker alternative (no daemon)"

echo ""
echo "System management deep dive complete."
