#!/bin/bash
echo "================================================"
echo "  Systemd Unit Files Reference"
echo "  Linux+ XK0-006 Study Guide"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "--- SYSTEMCTL COMMANDS ---"
echo ""
echo "  Service management:"
echo "    systemctl start nginx        Start now"
echo "    systemctl stop nginx         Stop now"
echo "    systemctl restart nginx      Stop then start"
echo "    systemctl reload nginx       Reload config (no downtime)"
echo "    systemctl status nginx       Check current state"
echo ""
echo "  Boot persistence:"
echo "    systemctl enable nginx       Start on boot"
echo "    systemctl disable nginx      Do NOT start on boot"
echo "    systemctl enable --now nginx Start now AND on boot"
echo ""
echo "  Investigation:"
echo "    systemctl is-active nginx    Returns active/inactive"
echo "    systemctl is-enabled nginx   Returns enabled/disabled"
echo "    systemctl list-units         All loaded units"
echo "    systemctl list-unit-files    All installed units"
echo "    systemctl list-units --failed  Show failed units"
echo ""
echo "  CRITICAL: enable does NOT start the service!"
echo "  CRITICAL: start does NOT survive reboot!"
echo "  Use enable --now for both."

echo ""
echo "--- UNIT FILE STRUCTURE ---"
echo ""
echo "  Location: /etc/systemd/system/ (custom)"
echo "  Location: /usr/lib/systemd/system/ (packages)"
echo ""
echo "  Example service unit file:"
echo "  /etc/systemd/system/myapp.service"
echo "  ----------------------------------------"
echo "  [Unit]"
echo "  Description=My Application Server"
echo "  After=network.target"
echo "  Wants=postgresql.service"
echo ""
echo "  [Service]"
echo "  Type=simple"
echo "  User=appuser"
echo "  Group=appgroup"
echo "  WorkingDirectory=/opt/myapp"
echo "  ExecStart=/opt/myapp/bin/server"
echo "  ExecReload=/bin/kill -HUP \$MAINPID"
echo "  Restart=on-failure"
echo "  RestartSec=5"
echo "  Environment=NODE_ENV=production"
echo ""
echo "  [Install]"
echo "  WantedBy=multi-user.target"
echo "  ----------------------------------------"

echo ""
echo "--- UNIT FILE SECTIONS ---"
echo ""
echo "  [Unit] - metadata and dependencies"
echo "    Description    What the service does"
echo "    After          Start after these units"
echo "    Before         Start before these units"
echo "    Wants          Weak dependency (start if available)"
echo "    Requires       Strong dependency (fail if missing)"
echo ""
echo "  [Service] - how to run the service"
echo "    Type           simple, forking, oneshot, notify"
echo "    ExecStart      Command to start the service"
echo "    ExecStop       Command to stop the service"
echo "    ExecReload     Command to reload config"
echo "    Restart        on-failure, always, no"
echo "    RestartSec     Seconds between restart attempts"
echo "    User/Group     Run as this user/group"
echo "    Environment    Set environment variables"
echo "    WorkingDirectory  Set working directory"
echo ""
echo "  [Install] - when to start"
echo "    WantedBy       multi-user.target (CLI boot)"
echo "                   graphical.target (GUI boot)"

echo ""
echo "--- SERVICE TYPES ---"
echo ""
echo "  simple     Default. Process stays in foreground."
echo "  forking    Process forks to background (like Apache)."
echo "  oneshot    Runs once and exits (like a script)."
echo "  notify     Like simple but signals when ready."
echo "  idle       Like simple but waits for other jobs."

echo ""
echo "--- TARGETS (RUNLEVELS) ---"
echo ""
echo "  Targets replaced runlevels in systemd:"
echo ""
echo "  poweroff.target     Runlevel 0  Shut down"
echo "  rescue.target       Runlevel 1  Single user mode"
echo "  multi-user.target   Runlevel 3  CLI with networking"
echo "  graphical.target    Runlevel 5  GUI desktop"
echo "  reboot.target       Runlevel 6  Reboot"
echo ""
echo "  Commands:"
echo "    systemctl get-default              Show default target"
echo "    systemctl set-default multi-user   Set CLI boot"
echo "    systemctl set-default graphical    Set GUI boot"
echo "    systemctl isolate rescue.target    Enter rescue mode"

echo ""
echo "--- JOURNALCTL (LOG VIEWER) ---"
echo ""
echo "  View logs:"
echo "    journalctl                    All logs"
echo "    journalctl -u nginx           Logs for one service"
echo "    journalctl -u nginx --since today   Today only"
echo "    journalctl -u nginx -f        Follow in real-time"
echo "    journalctl -p err             Errors only"
echo "    journalctl -b                 This boot only"
echo "    journalctl -b -1              Previous boot"
echo "    journalctl --disk-usage       Log storage used"
echo ""
echo "  Priority levels (exam tested):"
echo "    0 emerg     System is unusable"
echo "    1 alert     Immediate action needed"
echo "    2 crit      Critical conditions"
echo "    3 err       Error conditions"
echo "    4 warning   Warning conditions"
echo "    5 notice    Normal but significant"
echo "    6 info      Informational"
echo "    7 debug     Debug messages"
echo ""
echo "  journalctl -p err shows levels 0-3"

echo ""
echo "--- AFTER EDITING UNIT FILES ---"
echo ""
echo "  Always run:"
echo "    systemctl daemon-reload"
echo "  Then:"
echo "    systemctl restart <service>"
echo ""
echo "  daemon-reload tells systemd to re-read unit files."
echo "  Without it, systemd uses the old cached version."

echo ""
echo "Systemd reference complete."
