#!/bin/bash
echo "================================================"
echo "  Troubleshooting Methodology Reference"
echo "  Linux+ XK0-006 Domain 5: Troubleshooting"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "=== THE TROUBLESHOOTING PROCESS (exam tested) ==="
echo ""
echo "  1. Identify the problem"
echo "     - Gather information from the user"
echo "     - Reproduce the issue if possible"
echo "     - Determine scope (one user? all users? one server?)"
echo ""
echo "  2. Establish a theory"
echo "     - Start with the most likely cause"
echo "     - Consider simple things first (is it plugged in?)"
echo "     - Question the obvious"
echo ""
echo "  3. Test the theory"
echo "     - Verify your theory with commands/tests"
echo "     - If theory fails, go back to step 2"
echo ""
echo "  4. Create an action plan"
echo "     - Plan the fix before implementing"
echo "     - Consider impact and rollback"
echo ""
echo "  5. Implement the fix"
echo "     - Apply the solution"
echo "     - One change at a time"
echo ""
echo "  6. Verify full functionality"
echo "     - Confirm the problem is resolved"
echo "     - Test related systems"
echo ""
echo "  7. Document findings"
echo "     - Record what happened and how it was fixed"
echo "     - Update runbooks if applicable"

echo ""
echo "=== SERVICE WON'T START ==="
echo ""
echo "  Step-by-step:"
echo "    systemctl status service        What state is it in?"
echo "    journalctl -u service -n 50     What do the logs say?"
echo "    systemctl cat service           Is the unit file correct?"
echo "    ExecStart path exist?           ls -la /path/to/binary"
echo "    Config file valid?              Check syntax of config"
echo "    Port conflict?                  ss -tlnp | grep PORT"
echo "    Permissions?                    ls -la on binary and config"
echo "    SELinux?                        ausearch -m avc -ts recent"
echo "    Dependencies running?           systemctl list-dependencies"
echo ""
echo "  Common causes:"
echo "    - Typo in config file"
echo "    - Wrong permissions on binary or config"
echo "    - Port already in use by another service"
echo "    - SELinux blocking access"
echo "    - Missing dependency service"
echo "    - Binary not found (wrong ExecStart path)"

echo ""
echo "=== SYSTEM WON'T BOOT ==="
echo ""
echo "  Boot process order:"
echo "    BIOS/UEFI -> GRUB -> Kernel -> initramfs -> systemd"
echo ""
echo "  Stuck at GRUB:"
echo "    - GRUB config corrupted"
echo "    - Kernel image missing"
echo "    - Fix: boot from ISO, chroot, rebuild grub"
echo "    - grub2-mkconfig -o /boot/grub2/grub.cfg"
echo ""
echo "  Kernel panic:"
echo "    - Missing kernel modules"
echo "    - Corrupted initramfs"
echo "    - Fix: boot old kernel from GRUB menu"
echo "    - Rebuild: dracut --force"
echo ""
echo "  Stuck at systemd:"
echo "    - Failed service blocking boot"
echo "    - Bad /etc/fstab entry"
echo "    - Fix: boot to rescue.target"
echo "    - systemctl isolate rescue.target"
echo ""
echo "  Emergency shell:"
echo "    - File system corruption"
echo "    - Fix: fsck on the affected partition"
echo "    - ALWAYS unmount first or use rescue mode"
echo ""
echo "  fstab mount failure:"
echo "    - Wrong UUID"
echo "    - Missing partition"
echo "    - Wrong filesystem type"
echo "    - Fix: edit /etc/fstab from rescue mode"
echo "    - Use nofail option to prevent boot hang"

echo ""
echo "=== NETWORK TROUBLESHOOTING ==="
echo ""
echo "  Layer-by-layer approach:"
echo ""
echo "  1. Physical/Link layer:"
echo "     ip link show              Interface up or down?"
echo "     ip link set eth0 up      Bring interface up"
echo "     ethtool eth0              Link speed and status"
echo ""
echo "  2. IP layer:"
echo "     ip addr show              Do I have an IP?"
echo "     ip addr add 10.0.0.5/24 dev eth0   Set IP manually"
echo "     dhclient eth0             Request DHCP lease"
echo ""
echo "  3. Gateway:"
echo "     ip route show             Is there a default route?"
echo "     ping gateway_ip           Can I reach the gateway?"
echo "     ip route add default via 10.0.0.1  Add default route"
echo ""
echo "  4. DNS:"
echo "     cat /etc/resolv.conf      DNS servers configured?"
echo "     dig google.com            DNS resolving?"
echo "     nslookup hostname         Quick DNS test"
echo "     /etc/hosts                Check local overrides"
echo ""
echo "  5. Service/Port:"
echo "     ss -tlnp                  What ports are listening?"
echo "     nc -zv host port          Can I reach the port?"
echo "     curl http://host:port     Test HTTP service"
echo ""
echo "  6. Firewall:"
echo "     firewall-cmd --list-all   What's allowed through?"
echo "     iptables -L -n            Raw firewall rules"
echo "     ufw status                Ubuntu firewall"

echo ""
echo "=== DISK/STORAGE TROUBLESHOOTING ==="
echo ""
echo "  Disk full:"
echo "    df -h                      Which filesystem is full?"
echo "    du -sh /* | sort -rh       Biggest directories"
echo "    find / -size +100M         Large files"
echo "    journalctl --disk-usage    Log storage"
echo "    > /var/log/largefile       Truncate (don't rm open files)"
echo ""
echo "  Can't mount filesystem:"
echo "    blkid                      Check UUID and type"
echo "    fsck /dev/sdX              Check for corruption (UNMOUNT)"
echo "    mount -t type /dev/sdX /mnt  Specify type manually"
echo "    dmesg | tail               Kernel messages"
echo ""
echo "  LVM issues:"
echo "    pvs / vgs / lvs            Check each LVM layer"
echo "    vgchange -ay vg_name       Activate volume group"
echo "    lvchange -ay /dev/vg/lv    Activate logical volume"
echo ""
echo "  Inode exhaustion (disk not full but can't create files):"
echo "    df -i                      Check inode usage"
echo "    find / -xdev -type f | wc -l   Count files"
echo "    Many small files consume inodes without filling disk"

echo ""
echo "=== PERFORMANCE TROUBLESHOOTING ==="
echo ""
echo "  High CPU:"
echo "    top or htop                Find the process"
echo "    ps aux --sort=-%cpu        Sort by CPU"
echo "    renice 19 -p PID           Lower priority"
echo "    kill PID / kill -9 PID     Stop it"
echo ""
echo "  High memory:"
echo "    free -h                    How much is used?"
echo "    ps aux --sort=-%mem        Sort by memory"
echo "    vmstat 5                   Watch swap activity"
echo "    si/so columns > 0 = swapping (bad)"
echo ""
echo "  High I/O:"
echo "    iostat 5                   Disk I/O stats"
echo "    iotop                      Per-process I/O"
echo "    dmesg | grep error         Disk errors"
echo ""
echo "  Load average too high:"
echo "    uptime                     Check load averages"
echo "    Rule: load should be < number of CPU cores"
echo "    nproc                      Show CPU core count"

echo ""
echo "=== USER/PERMISSION TROUBLESHOOTING ==="
echo ""
echo "  Can't login:"
echo "    passwd -S user             Account status"
echo "    chage -l user              Password expiry"
echo "    grep user /etc/shadow      Is password locked (! or *)?"
echo "    faillog -u user            Failed login attempts"
echo "    /var/log/auth.log          Authentication logs"
echo "    /var/log/secure            RHEL auth logs"
echo ""
echo "  Permission denied:"
echo "    ls -la file                Check permissions"
echo "    ls -Z file                 Check SELinux context"
echo "    getfacl file               Check ACLs"
echo "    namei -l /full/path        Check each directory in path"
echo ""
echo "  sudo not working:"
echo "    grep user /etc/sudoers     User in sudoers?"
echo "    groups user                User in sudo/wheel group?"
echo "    visudo -c                  Syntax check sudoers"

echo ""
echo "=== LOG FILE LOCATIONS ==="
echo ""
echo "  /var/log/syslog          General system log (Debian)"
echo "  /var/log/messages        General system log (RHEL)"
echo "  /var/log/auth.log        Authentication (Debian)"
echo "  /var/log/secure          Authentication (RHEL)"
echo "  /var/log/kern.log        Kernel messages"
echo "  /var/log/boot.log        Boot process"
echo "  /var/log/dmesg           Hardware/driver messages"
echo "  /var/log/cron            Cron job logs"
echo "  /var/log/audit/audit.log SELinux audit log"
echo "  journalctl               Systemd journal (all logs)"

echo ""
echo "=== EXAM TIPS FOR TROUBLESHOOTING ==="
echo ""
echo "  1. Read the ENTIRE question - what symptom?"
echo "  2. What changed? (update, config change, new install)"
echo "  3. Start with the simplest explanation"
echo "  4. Check logs FIRST - they usually tell you the answer"
echo "  5. Know which log file to check for which problem"
echo "  6. Don't skip steps - go layer by layer"
echo "  7. 'It was working yesterday' = something changed"

echo ""
echo "Troubleshooting reference complete."
