#!/bin/bash
echo "================================================"
echo "  User and Group Management Reference"
echo "  Linux+ XK0-006 Study Guide"
echo "  Date: $(date)"
echo "================================================"

echo ""
echo "--- USER COMMANDS ---"
echo ""
echo "  Create users:"
echo "    useradd john                 Create user (no home dir on some distros)"
echo "    useradd -m john              Create user WITH home directory"
echo "    useradd -m -s /bin/bash john  Set login shell"
echo "    useradd -m -G sudo,dev john   Add to groups at creation"
echo "    useradd -m -c 'John Smith' john   Add comment/full name"
echo "    useradd -m -e 2026-12-31 john     Set expiration date"
echo "    useradd -r svcaccount        Create system/service account"
echo ""
echo "  Modify users:"
echo "    usermod -aG docker john      Add to group (KEEP existing groups)"
echo "    usermod -G docker john       Set groups (REPLACES all groups!)"
echo "    usermod -s /bin/zsh john     Change shell"
echo "    usermod -l newname john      Rename user"
echo "    usermod -L john              Lock account"
echo "    usermod -U john              Unlock account"
echo "    usermod -d /new/home john    Change home directory"
echo ""
echo "  CRITICAL: -aG vs -G"
echo "    -aG = APPEND to existing groups (what you want)"
echo "    -G  = REPLACE all groups (dangerous!)"
echo ""
echo "  Delete users:"
echo "    userdel john                 Delete user (keep home)"
echo "    userdel -r john              Delete user AND home directory"
echo ""
echo "  Set password:"
echo "    passwd john                  Set/change password"
echo "    passwd -l john               Lock account"
echo "    passwd -u john               Unlock account"
echo "    passwd -e john               Force password change at next login"

echo ""
echo "--- GROUP COMMANDS ---"
echo ""
echo "  groupadd developers           Create group"
echo "  groupmod -n devteam developers Rename group"
echo "  groupdel developers           Delete group"
echo "  gpasswd -a john developers    Add user to group"
echo "  gpasswd -d john developers    Remove user from group"
echo "  groups john                   Show user groups"
echo "  id john                       Show uid, gid, all groups"
echo "  newgrp developers             Switch primary group (current session)"

echo ""
echo "--- KEY FILES ---"
echo ""
echo "  /etc/passwd - User accounts (world readable)"
echo "    Format: username:x:UID:GID:comment:home:shell"
echo "    Example: john:x:1001:1001:John Smith:/home/john:/bin/bash"
echo ""
echo "    Fields:"
echo "      username    Login name"
echo "      x           Password stored in /etc/shadow"
echo "      UID         User ID (0=root, 1000+=regular users)"
echo "      GID         Primary group ID"
echo "      comment     Full name or description"
echo "      home        Home directory path"
echo "      shell       Login shell (/bin/bash, /sbin/nologin)"
echo ""
echo "  /etc/shadow - Password hashes (root only, 600)"
echo "    Format: username:hash:lastchange:min:max:warn:inactive:expire"
echo "    Example: john:\$6\$salt\$hash:19517:0:99999:7:::"
echo ""
echo "    Fields:"
echo "      hash        Encrypted password"
echo "      lastchange  Days since epoch password was changed"
echo "      min         Min days between password changes"
echo "      max         Max days before password must change"
echo "      warn        Days before expiry to warn user"
echo "      inactive    Days after expiry account is disabled"
echo "      expire      Account expiration date"
echo ""
echo "  /etc/group - Group definitions"
echo "    Format: groupname:x:GID:members"
echo "    Example: developers:x:1002:john,jane,bob"
echo ""
echo "  /etc/gshadow - Group passwords (rarely used)"
echo ""
echo "  /etc/login.defs - Default settings for user creation"
echo "    UID_MIN, UID_MAX, PASS_MAX_DAYS, PASS_MIN_LEN"
echo ""
echo "  /etc/skel/ - Skeleton directory"
echo "    Files here are copied to every new user home directory"
echo "    .bashrc, .profile, etc."

echo ""
echo "--- PASSWORD AGING (chage) ---"
echo ""
echo "  chage -l john               List aging info"
echo "  chage -M 90 john            Password expires after 90 days"
echo "  chage -m 7 john             Min 7 days between changes"
echo "  chage -W 14 john            Warn 14 days before expiry"
echo "  chage -E 2026-12-31 john    Account expires on date"
echo "  chage -d 0 john             Force password change at next login"
echo ""
echo "  Password aging in /etc/login.defs sets system defaults"
echo "  chage overrides per user"

echo ""
echo "--- UID RANGES ---"
echo ""
echo "  0           root (always)"
echo "  1-999       System/service accounts"
echo "  1000+       Regular human users"
echo ""
echo "  On macOS: regular users start at 501"
echo "  On Linux: regular users start at 1000"

echo ""
echo "--- SHELL TYPES ---"
echo ""
echo "  /bin/bash         Standard interactive shell"
echo "  /bin/zsh          Z shell (macOS default)"
echo "  /bin/sh           Bourne shell (scripts)"
echo "  /sbin/nologin     Prevents login (for service accounts)"
echo "  /bin/false        Also prevents login"
echo ""
echo "  Change shell: chsh -s /bin/zsh john"
echo "  List shells: cat /etc/shells"

echo ""
echo "--- SUDO CONFIGURATION ---"
echo ""
echo "  /etc/sudoers - NEVER edit directly"
echo "  Always use: visudo"
echo ""
echo "  Syntax: user  host=(runas)  commands"
echo "  Examples:"
echo "    john ALL=(ALL) ALL                Full sudo access"
echo "    john ALL=(ALL) NOPASSWD: ALL      No password required"
echo "    john ALL=(root) /usr/bin/systemctl Only systemctl"
echo "    %admin ALL=(ALL) ALL              Group admin gets sudo"
echo ""
echo "  Drop-in files: /etc/sudoers.d/"
echo "    visudo -f /etc/sudoers.d/john"
echo "    Cleaner than editing main sudoers"

echo ""
echo "User and group management reference complete."
